"""Agent installation script generation service.

Generates platform-specific installation scripts for agent deployment.
Supports bash scripts for Unix systems and PowerShell scripts for Windows.
"""

from hydra.api.v1 import __version__
from hydra.api.v1.services.storage import StorageSource


class InstallScriptService:
    """Service for generating agent installation scripts."""

    def __init__(self, api_version: str = __version__):
        self.api_version = api_version

    def generate_bash_script(
        self,
        api_url: str,
        source: StorageSource = StorageSource.BINARY,
        version: str = "latest",
    ) -> str:
        """Generate bash installation script for Unix systems.

        Args:
            api_url: Base API URL for downloads.
            source: Storage source for bundles.
            version: Version to install.

        Returns:
            Bash script content.
        """
        source_value = source.value
        return fr'''#!/bin/bash
#
# Hydra Agent Installer (API wrapper)
# Generated by hydra-api v{self.api_version}
#
# Usage:
#   curl -sSL {api_url}/agent/install?source=local|obs | bash -s -- [OPTIONS]
#
# Options (forwarded to hydra-agent/scripts/install.sh):
#   -v, --version <VER>     Version number for binary manifest (required)
#   -h, --help              Show help
#   -a, --aliased           Create 'hydra' alias
#   -g, --global            Add to PATH globally
#   -d, --install-dir <DIR> Installation directory [default: /usr/local/bin]
#   -c, --config <PATH>     Config file path [default: /etc/hydra/agent.toml]
#   -r, --register <TOKEN>  Auto-register with token after install
#
set -euo pipefail

API_URL="{api_url}"
SOURCE="{source_value}"
DEFAULT_VERSION="{version}"

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

info()    {{ echo -e "${{BLUE}}[INFO]${{NC}} $*"; }}
warn()    {{ echo -e "${{YELLOW}}[WARN]${{NC}} $*"; }}
error()   {{ echo -e "${{RED}}[ERROR]${{NC}} $*" >&2; }}
success() {{ echo -e "${{GREEN}}[OK]${{NC}} $*"; }}

TMP_DIR=""
AGENT_ROOT=""
INSTALL_SCRIPT=""
USER_ARGS=()
REQUESTED_VERSION=""
HAS_VERSION="false"

parse_args() {{
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -v|--version)
                if [[ -z "${{2:-}}" ]]; then
                    error "Missing value for $1"
                    exit 1
                fi
                REQUESTED_VERSION="$2"
                HAS_VERSION="true"
                USER_ARGS+=("$1" "$2")
                shift 2
                ;;
            *)
                USER_ARGS+=("$1")
                shift
                ;;
        esac
    done
}}

check_prereqs() {{
    if ! command -v curl >/dev/null 2>&1; then
        error "curl is required but not installed"
        exit 1
    fi
    if ! command -v unzip >/dev/null 2>&1; then
        error "unzip is required but not installed"
        exit 1
    fi
}}

download_bundle() {{
    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT

    local download_url="$API_URL/agent/download?source=$SOURCE&version=$REQUESTED_VERSION"
    info "Downloading agent bundle (source=$SOURCE, version=$REQUESTED_VERSION)..."

    curl -sSL -f -o "$TMP_DIR/hydra-agent.zip" "$download_url" || {{
        error "Failed to download agent bundle"
        exit 1
    }}

    info "Extracting bundle..."
    mkdir -p "$TMP_DIR/bundle"
    unzip -q "$TMP_DIR/hydra-agent.zip" -d "$TMP_DIR/bundle" || {{
        error "Failed to extract bundle"
        exit 1
    }}
}}

find_installer() {{
    local install_script
    install_script=$(find "$TMP_DIR/bundle" -path "*/scripts/install.sh" -type f | head -1)
    if [[ -z "$install_script" ]]; then
        error "install.sh not found in bundle"
        exit 1
    fi

    AGENT_ROOT=$(cd "$(dirname "$install_script")/.." && pwd)
    INSTALL_SCRIPT="$install_script"
}}

run_installer() {{
    info "Running hydra-agent installer..."
    (cd "$AGENT_ROOT" && HYDRA_API_URL="$API_URL" bash "$INSTALL_SCRIPT" "${{USER_ARGS[@]}}")
}}

main() {{
    if [[ "$SOURCE" != "obs" && "$SOURCE" != "local" ]]; then
        error "Unsupported source for /agent/install: $SOURCE"
        error "Use ?source=local or ?source=obs"
        exit 1
    fi

    parse_args "$@"

    if [[ "$HAS_VERSION" != "true" ]]; then
        REQUESTED_VERSION="$DEFAULT_VERSION"
        USER_ARGS+=("-v" "$REQUESTED_VERSION")
    fi

    check_prereqs
    download_bundle
    find_installer
    run_installer
}}

main "$@"
'''

    def generate_binary_bash_script(
        self,
        api_url: str,
        version: str = "latest",
    ) -> str:
        """Generate a prebuilt-binary bash installer for Unix systems.

        Unlike :meth:`generate_bash_script` (which downloads a source bundle and
        compiles the agent with cargo on the target), this script downloads a
        pre-compiled binary from object storage, verifies its SHA256 checksum,
        installs it, writes a config file (API URL derived from the request,
        node_id derived from the hostname), and — when a registration token is
        supplied — performs a full headless bootstrap via ``hydra-agent
        bootstrap``.

        Args:
            api_url: Base API URL for downloads (derived from the request).
            version: Version to install (``latest`` resolves per target).

        Returns:
            Bash script content.
        """
        return fr'''#!/bin/bash
#
# Hydra Agent Installer (prebuilt binary)
# Generated by hydra-api v{self.api_version}
#
# Usage:
#   curl -sSL {api_url}/agent/install | bash -s -- [OPTIONS]
#
# Options:
#   -v, --version <VER>     Version to install [default: latest]
#   -d, --install-dir <DIR> Installation directory [default: /usr/local/bin]
#   -c, --config <PATH>     Config file path [default: /etc/hydra/agent.toml]
#   -a, --aliased           Create 'hydra' alias symlink
#   -g, --global            Add install directory to PATH globally
#       --node-id <ID>      Node identifier (default: derived from hostname)
#       --tier <TIER>       Agent tier: lite|normal|max [default: normal]
#   -r, --register <TOKEN>  Headless bootstrap (register + node + service + first profile)
#   -h, --help              Show help
#
set -euo pipefail

API_URL="{api_url}"
DEFAULT_VERSION="{version}"

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
CYAN='\\033[0;36m'
NC='\\033[0m'

info()    {{ echo -e "${{BLUE}}[INFO]${{NC}} $*"; }}
warn()    {{ echo -e "${{YELLOW}}[WARN]${{NC}} $*"; }}
error()   {{ echo -e "${{RED}}[ERROR]${{NC}} $*" >&2; }}
success() {{ echo -e "${{GREEN}}[OK]${{NC}} $*"; }}
step()    {{ echo -e "${{CYAN}}[STEP]${{NC}} $*"; }}

INSTALL_DIR="/usr/local/bin"
CONFIG_FILE="/etc/hydra/agent.toml"
CONFIG_DIR="/etc/hydra"
VAULT_DIR="/var/cv/hydra"
LOG_DIR="/var/log/hydra"
CREATE_ALIAS=false
ADD_TO_PATH=false
REGISTER_TOKEN=""
NODE_ID=""
TIER="normal"
REQUESTED_VERSION="$DEFAULT_VERSION"
TARGET=""
SUDO=""
TMP_DIR=""
EXPECTED_SHA=""
RESOLVED_VERSION=""

show_help() {{
    grep '^#' "$0" 2>/dev/null | sed 's/^# \\{{0,1\\}}//' || true
    cat <<'EOF'
Hydra Agent Installer (prebuilt binary)

Options:
  -v, --version <VER>     Version to install [default: latest]
  -d, --install-dir <DIR> Installation directory [default: /usr/local/bin]
  -c, --config <PATH>     Config file path [default: /etc/hydra/agent.toml]
  -a, --aliased           Create 'hydra' alias symlink
  -g, --global            Add install directory to PATH globally
      --node-id <ID>      Node identifier (default: derived from hostname)
      --tier <TIER>       Agent tier: lite|normal|max [default: normal]
  -r, --register <TOKEN>  Headless bootstrap (register + node + service + first profile)
  -h, --help              Show this help
EOF
}}

parse_args() {{
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -v|--version)      REQUESTED_VERSION="${{2:?missing value for $1}}"; shift 2;;
            -d|--install-dir)  INSTALL_DIR="${{2:?missing value for $1}}"; shift 2;;
            -c|--config)       CONFIG_FILE="${{2:?missing value for $1}}"; CONFIG_DIR=$(dirname "$CONFIG_FILE"); shift 2;;
            -a|--aliased)      CREATE_ALIAS=true; shift;;
            -g|--global)       ADD_TO_PATH=true; shift;;
            --node-id)         NODE_ID="${{2:?missing value for $1}}"; shift 2;;
            --tier)            TIER="${{2:?missing value for $1}}"; shift 2;;
            -r|--register)     REGISTER_TOKEN="${{2:?missing value for $1}}"; shift 2;;
            -h|--help)         show_help; exit 0;;
            *)                 error "Unknown option: $1"; show_help; exit 1;;
        esac
    done
}}

setup_sudo() {{
    if [[ "$(id -u)" -ne 0 ]]; then
        if command -v sudo >/dev/null 2>&1; then
            SUDO="sudo"
        else
            error "Root privileges are required (install sudo or run as root)"
            exit 1
        fi
    fi
}}

check_prereqs() {{
    if ! command -v curl >/dev/null 2>&1; then
        error "curl is required but not installed"
        exit 1
    fi
    if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
        warn "Neither sha256sum nor shasum found; checksum verification will be skipped"
    fi
}}

detect_target() {{
    local os arch
    os=$(uname -s | tr '[:upper:]' '[:lower:]')
    arch=$(uname -m)
    case "$arch" in
        x86_64|amd64)   arch="amd64";;
        aarch64|arm64)  arch="arm64";;
        armv7l|armv7)   arch="armv7";;
    esac
    case "${{os}}-${{arch}}" in
        linux-amd64|linux-arm64|linux-armv7|darwin-amd64|darwin-arm64|freebsd-amd64)
            TARGET="${{os}}-${{arch}}";;
        *)
            error "Unsupported platform: ${{os}}-${{arch}}"
            error "Supported: linux-amd64, linux-arm64, linux-armv7, darwin-amd64, darwin-arm64, freebsd-amd64"
            exit 1;;
    esac
    info "Detected platform: $TARGET"
}}

download_binary() {{
    step "Downloading prebuilt binary (target=$TARGET, version=$REQUESTED_VERSION)..."
    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT

    local url="$API_URL/agent/download?source=binary&target=$TARGET&version=$REQUESTED_VERSION"
    if ! curl -sSL -f -D "$TMP_DIR/headers.txt" -o "$TMP_DIR/hydra-agent" "$url"; then
        error "Failed to download binary for $TARGET (version $REQUESTED_VERSION)"
        error "If no prebuilt binary exists for this platform, build from source instead:"
        error "  curl -sSL '$API_URL/agent/install?source=obs' | bash -s -- -v $REQUESTED_VERSION"
        exit 1
    fi

    EXPECTED_SHA=$(grep -i '^x-checksum-sha256:' "$TMP_DIR/headers.txt" | tail -1 | awk '{{print $2}}' | tr -d '\\r' || true)
    RESOLVED_VERSION=$(grep -i '^x-hydra-version:' "$TMP_DIR/headers.txt" | tail -1 | awk '{{print $2}}' | tr -d '\\r' || true)
    [[ -n "$RESOLVED_VERSION" ]] && REQUESTED_VERSION="$RESOLVED_VERSION"
}}

verify_checksum() {{
    if [[ -z "$EXPECTED_SHA" ]]; then
        warn "Server did not provide a checksum; skipping verification"
        return
    fi
    local actual
    if command -v sha256sum >/dev/null 2>&1; then
        actual=$(sha256sum "$TMP_DIR/hydra-agent" | awk '{{print $1}}')
    elif command -v shasum >/dev/null 2>&1; then
        actual=$(shasum -a 256 "$TMP_DIR/hydra-agent" | awk '{{print $1}}')
    else
        return
    fi
    if [[ "$actual" != "$EXPECTED_SHA" ]]; then
        error "Checksum verification failed!"
        error "  expected: $EXPECTED_SHA"
        error "  actual:   $actual"
        exit 1
    fi
    success "Checksum verified (SHA256)"
}}

install_binary() {{
    step "Installing binary to $INSTALL_DIR/hydra-agent..."
    $SUDO mkdir -p "$INSTALL_DIR"
    $SUDO install -m 0755 "$TMP_DIR/hydra-agent" "$INSTALL_DIR/hydra-agent"
    if [[ "$CREATE_ALIAS" == "true" ]]; then
        $SUDO ln -sf "$INSTALL_DIR/hydra-agent" "$INSTALL_DIR/hydra"
        info "Created alias: hydra -> hydra-agent"
    fi
    success "Installed $($SUDO "$INSTALL_DIR/hydra-agent" --version 2>/dev/null || echo hydra-agent)"
}}

setup_directories() {{
    $SUDO mkdir -p "$CONFIG_DIR" "$LOG_DIR"
    if [[ ! -d "$VAULT_DIR" ]]; then
        $SUDO mkdir -p "$VAULT_DIR"
        $SUDO chmod 700 "$VAULT_DIR"
    fi
}}

derive_node_id() {{
    if [[ -n "$NODE_ID" ]]; then
        return
    fi
    local raw
    raw=$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo "node")
    # Lowercase, replace invalid chars with '-', collapse repeats, trim separators.
    NODE_ID=$(echo "$raw" \
        | LC_ALL=C tr '[:upper:]' '[:lower:]' \
        | LC_ALL=C sed -E 's/[^a-z0-9._-]+/-/g; s/[-._]{{2,}}/-/g; s/^[-._]+//; s/[-._]+$//')
    if [[ -z "$NODE_ID" || ! "$NODE_ID" =~ ^[a-z0-9] || ${{#NODE_ID}} -lt 3 ]]; then
        NODE_ID="node-$(echo "$raw" | sha256sum 2>/dev/null | cut -c1-8 || echo "$$")"
    fi
    info "Derived node_id: $NODE_ID"
}}

setup_config() {{
    if [[ -f "$CONFIG_FILE" ]]; then
        info "Configuration already exists at $CONFIG_FILE (left unchanged)"
        return
    fi
    step "Writing configuration to $CONFIG_FILE..."
    $SUDO mkdir -p "$CONFIG_DIR"
    $SUDO tee "$CONFIG_FILE" >/dev/null <<EOF
# Hydra Agent Configuration (generated by installer)
[node]
node_id = "$NODE_ID"
class = "compute"
tier = "$TIER"
node_type = "physical"

[api]
url = "$API_URL"
timeout_seconds = 30
retries = 3

[collection]
level = "neutral"
collectors = ["hardware", "network", "storage", "software", "services"]
include_packages = true
include_users = true

[schedule]
enabled = true
interval_seconds = 21600
on_startup = true
poll_interval_seconds = 30
EOF
    $SUDO chmod 644 "$CONFIG_FILE"
    success "Configuration written"
}}

setup_path() {{
    [[ "$ADD_TO_PATH" == "true" ]] || return
    if [[ -d /etc/profile.d ]]; then
        $SUDO tee /etc/profile.d/hydra-agent.sh >/dev/null <<EOF
export PATH="\\$PATH:$INSTALL_DIR"
EOF
        info "Added $INSTALL_DIR to system PATH (new shells)"
    fi
}}

bootstrap_agent() {{
    if [[ -z "$REGISTER_TOKEN" ]]; then
        return
    fi
    step "Running headless bootstrap (register + node + service + first profile)..."
    if $SUDO "$INSTALL_DIR/hydra-agent" -c "$CONFIG_FILE" bootstrap --token "$REGISTER_TOKEN"; then
        success "Headless bootstrap complete"
    else
        warn "Bootstrap did not fully complete. Re-run manually with:"
        warn "  sudo $INSTALL_DIR/hydra-agent -c $CONFIG_FILE bootstrap --token <token>"
        exit 1
    fi
}}

print_summary() {{
    echo ""
    success "Hydra Agent installed: $INSTALL_DIR/hydra-agent (version $REQUESTED_VERSION)"
    info "Config: $CONFIG_FILE   Node: $NODE_ID"
    if [[ -z "$REGISTER_TOKEN" ]]; then
        echo ""
        echo "Next steps (no registration token provided):"
        echo "  sudo $INSTALL_DIR/hydra-agent -c $CONFIG_FILE bootstrap --token <token>"
        echo "or run the steps individually: register / node register / service activate / run --once"
    fi
    echo ""
}}

main() {{
    parse_args "$@"
    setup_sudo
    check_prereqs
    detect_target
    download_binary
    verify_checksum
    install_binary
    setup_directories
    derive_node_id
    setup_config
    setup_path
    bootstrap_agent
    print_summary
}}

main "$@"
'''

    def generate_powershell_script(
        self,
        api_url: str,
        source: StorageSource = StorageSource.BINARY,
        version: str = "latest",
    ) -> str:
        """Generate PowerShell installation script for Windows.

        Args:
            api_url: Base API URL for downloads.
            source: Storage source for binaries.
            version: Version to install.

        Returns:
            PowerShell script content.
        """
        source_value = source.value
        return f'''#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Hydra Agent Installer for Windows (API wrapper)
    Generated by hydra-api v{self.api_version}

.DESCRIPTION
    Downloads and installs the Hydra Agent on Windows systems.

.PARAMETER Version
    Version to install (default: latest)

.PARAMETER InstallDir
    Installation directory (default: C:\\Program Files\\Hydra)

.PARAMETER RegisterToken
    Optional registration token for auto-registration

.PARAMETER CreateAlias
    Create 'hydra' alias for hydra-agent

.EXAMPLE
    iwr -useb {api_url}/agent/install | iex

.EXAMPLE
    iwr -useb "{api_url}/agent/install?version=0.3.1" | iex
#>

param(
    [string]$Version = "{version}",
    [string]$InstallDir = "$env:ProgramFiles\\Hydra",
    [string]$RegisterToken = "",
    [string]$NodeId = "",
    [string]$Tier = "normal",
    [switch]$CreateAlias
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$ApiUrl = "{api_url}"
$Source = "{source_value}"

function Write-Info {{ param([string]$Message) Write-Host "[INFO] $Message" -ForegroundColor Blue }}
function Write-Success {{ param([string]$Message) Write-Host "[OK] $Message" -ForegroundColor Green }}
function Write-Warn {{ param([string]$Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }}
function Write-Err {{ param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }}

function Test-Administrator {{
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}}

if (-not (Test-Administrator)) {{
    Write-Err "This script requires Administrator privileges."
    Write-Err "Please run PowerShell as Administrator and try again."
    exit 1
}}

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "   Hydra Agent Installer (Windows)"
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Create directories
Write-Info "Creating directories..."
$ConfigDir = "C:\\ProgramData\\Hydra"
$VaultDir = "C:\\ProgramData\\Hydra\\vault"
$LogDir = "C:\\ProgramData\\Hydra\\logs"

foreach ($dir in @($InstallDir, $ConfigDir, $VaultDir, $LogDir)) {{
    if (-not (Test-Path $dir)) {{
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }}
}}

# Set secure permissions on vault directory
Write-Info "Setting secure permissions on vault..."
$acl = Get-Acl $VaultDir
$acl.SetAccessRuleProtection($true, $false)
$adminRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
)
$systemRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
)
$acl.AddAccessRule($adminRule)
$acl.AddAccessRule($systemRule)
Set-Acl -Path $VaultDir -AclObject $acl

# Download binary
$DownloadUrl = "$ApiUrl/agent/download?source=binary&target=windows-amd64&version=$Version"
$BinaryPath = "$InstallDir\\hydra-agent.exe"

Write-Info "Downloading hydra-agent (version: $Version)..."
try {{
    $resp = Invoke-WebRequest -Uri $DownloadUrl -OutFile $BinaryPath -UseBasicParsing -PassThru
    Write-Success "Downloaded hydra-agent.exe"
}} catch {{
    Write-Err "Failed to download binary: $_"
    exit 1
}}

# Verify SHA256 checksum if the server provided one
$ExpectedSha = $null
if ($resp -and $resp.Headers -and $resp.Headers["X-Checksum-SHA256"]) {{
    $ExpectedSha = ([string]($resp.Headers["X-Checksum-SHA256"])).Trim().ToLower()
}}
if ($resp -and $resp.Headers -and $resp.Headers["X-Hydra-Version"]) {{
    $Version = ([string]($resp.Headers["X-Hydra-Version"])).Trim()
}}
if ($ExpectedSha) {{
    $ActualSha = (Get-FileHash -Path $BinaryPath -Algorithm SHA256).Hash.ToLower()
    if ($ActualSha -ne $ExpectedSha) {{
        Write-Err "Checksum verification failed (expected $ExpectedSha, got $ActualSha)"
        Remove-Item $BinaryPath -Force -ErrorAction SilentlyContinue
        exit 1
    }}
    Write-Success "Checksum verified (SHA256)"
}} else {{
    Write-Warn "Server did not provide a checksum; skipping verification"
}}

# Create alias if requested
if ($CreateAlias) {{
    $AliasPath = "$InstallDir\\hydra.exe"
    if (Test-Path $AliasPath) {{ Remove-Item $AliasPath -Force }}
    Copy-Item $BinaryPath $AliasPath
    Write-Info "Created alias: hydra.exe"
}}

# Add to PATH if not already present
$EnvPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
if ($EnvPath -notlike "*$InstallDir*") {{
    Write-Info "Adding to system PATH..."
    [Environment]::SetEnvironmentVariable("Path", "$EnvPath;$InstallDir", "Machine")
    $env:Path = "$env:Path;$InstallDir"
    Write-Success "Added to PATH"
}}

# Derive node_id from the computer name if not supplied
if (-not $NodeId) {{
    $raw = $env:COMPUTERNAME
    if (-not $raw) {{ $raw = "node" }}
    $NodeId = ($raw.ToLower() -replace '[^a-z0-9._-]+', '-') -replace '(^[-._]+)|([-._]+$)', ''
    if (-not $NodeId -or $NodeId.Length -lt 3 -or $NodeId[0] -notmatch '[a-z0-9]') {{
        $NodeId = "node-" + ($raw.ToLower() -replace '[^a-z0-9]', '')
    }}
}}
Write-Info "Node ID: $NodeId"

# Create default config if not exists
$ConfigFile = "$ConfigDir\\agent.toml"
if (-not (Test-Path $ConfigFile)) {{
    Write-Info "Creating default configuration..."
    @"
# Hydra Agent Configuration (generated by installer)

[node]
node_id = "$NodeId"
class = "compute"
tier = "$Tier"
node_type = "physical"

[api]
url = "$ApiUrl"
timeout_seconds = 30
retries = 3

[collection]
level = "neutral"
collectors = ["hardware", "network", "storage", "software", "services"]
include_packages = true
include_users = true

[schedule]
enabled = true
interval_seconds = 21600
on_startup = true
poll_interval_seconds = 30
"@ | Set-Content -Path $ConfigFile -Encoding UTF8
    Write-Success "Created config at $ConfigFile"
}} else {{
    Write-Info "Configuration already exists at $ConfigFile (left unchanged)"
}}

# Headless bootstrap if a registration token is provided
if ($RegisterToken) {{
    Write-Info "Running headless bootstrap (register + node + service + first profile)..."
    & "$BinaryPath" --config $ConfigFile bootstrap --token $RegisterToken
    if ($LASTEXITCODE -ne 0) {{
        Write-Err "Bootstrap did not fully complete. Re-run manually with:"
        Write-Err "  & '$BinaryPath' --config $ConfigFile bootstrap --token <token>"
        exit 1
    }}
    Write-Success "Headless bootstrap complete"
}}

Write-Host ""
Write-Success "Installation complete!"
Write-Host ""
if (-not $RegisterToken) {{
    Write-Host "Next steps (no registration token provided):" -ForegroundColor Cyan
    Write-Host "  & '$BinaryPath' --config $ConfigFile bootstrap --token <token>"
    Write-Host "or run individually: register / node register / service install / run --once"
    Write-Host ""
}}
'''


# Module-level instance for convenience
_install_service: InstallScriptService | None = None


def get_install_service() -> InstallScriptService:
    """Get or create the install script service singleton.

    Returns:
        InstallScriptService instance.
    """
    global _install_service
    if _install_service is None:
        _install_service = InstallScriptService()
    return _install_service
