"""Agent installation script generation service.

Generates platform-specific installation scripts for agent deployment.
Supports bash scripts for Unix systems and PowerShell scripts for Windows.
"""

from hydra.api.v1 import __version__
from hydra.api.v1.services.storage import StorageSource


class InstallScriptService:
    """Service for generating agent installation scripts."""

    def __init__(self, api_version: str = __version__):
        self.api_version = api_version

    def generate_bash_script(
        self,
        api_url: str,
        source: StorageSource = StorageSource.BINARY,
        version: str = "latest",
    ) -> str:
        """Generate bash installation script for Unix systems.

        Args:
            api_url: Base API URL for downloads.
            source: Storage source for bundles.
            version: Version to install.

        Returns:
            Bash script content.
        """
        source_value = source.value
        return fr'''#!/bin/bash
#
# Hydra Agent Installer (API wrapper)
# Generated by hydra-api v{self.api_version}
#
# Usage:
#   curl -sSL {api_url}/agent/install?source=local|obs | bash -s -- [OPTIONS]
#
# Options (forwarded to hydra-agent/scripts/install.sh):
#   -v, --version <VER>     Version number for binary manifest (required)
#   -h, --help              Show help
#   -a, --aliased           Create 'hydra' alias
#   -g, --global            Add to PATH globally
#   -d, --install-dir <DIR> Installation directory [default: /usr/local/bin]
#   -c, --config <PATH>     Config file path [default: /etc/hydra/agent.toml]
#   -r, --register <TOKEN>  Auto-register with token after install
#
set -euo pipefail

API_URL="{api_url}"
SOURCE="{source_value}"
DEFAULT_VERSION="{version}"

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

info()    {{ echo -e "${{BLUE}}[INFO]${{NC}} $*"; }}
warn()    {{ echo -e "${{YELLOW}}[WARN]${{NC}} $*"; }}
error()   {{ echo -e "${{RED}}[ERROR]${{NC}} $*" >&2; }}
success() {{ echo -e "${{GREEN}}[OK]${{NC}} $*"; }}

TMP_DIR=""
AGENT_ROOT=""
INSTALL_SCRIPT=""
USER_ARGS=()
REQUESTED_VERSION=""
HAS_VERSION="false"

parse_args() {{
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -v|--version)
                if [[ -z "${{2:-}}" ]]; then
                    error "Missing value for $1"
                    exit 1
                fi
                REQUESTED_VERSION="$2"
                HAS_VERSION="true"
                USER_ARGS+=("$1" "$2")
                shift 2
                ;;
            *)
                USER_ARGS+=("$1")
                shift
                ;;
        esac
    done
}}

check_prereqs() {{
    if ! command -v curl >/dev/null 2>&1; then
        error "curl is required but not installed"
        exit 1
    fi
    if ! command -v unzip >/dev/null 2>&1; then
        error "unzip is required but not installed"
        exit 1
    fi
}}

download_bundle() {{
    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT

    local download_url="$API_URL/agent/download?source=$SOURCE&version=$REQUESTED_VERSION"
    info "Downloading agent bundle (source=$SOURCE, version=$REQUESTED_VERSION)..."

    curl -sSL -f -o "$TMP_DIR/hydra-agent.zip" "$download_url" || {{
        error "Failed to download agent bundle"
        exit 1
    }}

    info "Extracting bundle..."
    mkdir -p "$TMP_DIR/bundle"
    unzip -q "$TMP_DIR/hydra-agent.zip" -d "$TMP_DIR/bundle" || {{
        error "Failed to extract bundle"
        exit 1
    }}
}}

find_installer() {{
    local install_script
    install_script=$(find "$TMP_DIR/bundle" -path "*/scripts/install.sh" -type f | head -1)
    if [[ -z "$install_script" ]]; then
        error "install.sh not found in bundle"
        exit 1
    fi

    AGENT_ROOT=$(cd "$(dirname "$install_script")/.." && pwd)
    INSTALL_SCRIPT="$install_script"
}}

run_installer() {{
    info "Running hydra-agent installer..."
    (cd "$AGENT_ROOT" && HYDRA_API_URL="$API_URL" bash "$INSTALL_SCRIPT" "${{USER_ARGS[@]}}")
}}

main() {{
    if [[ "$SOURCE" != "obs" && "$SOURCE" != "local" ]]; then
        error "Unsupported source for /agent/install: $SOURCE"
        error "Use ?source=local or ?source=obs"
        exit 1
    fi

    parse_args "$@"

    if [[ "$HAS_VERSION" != "true" ]]; then
        REQUESTED_VERSION="$DEFAULT_VERSION"
        USER_ARGS+=("-v" "$REQUESTED_VERSION")
    fi

    check_prereqs
    download_bundle
    find_installer
    run_installer
}}

main "$@"
'''

    def generate_powershell_script(
        self,
        api_url: str,
        source: StorageSource = StorageSource.BINARY,
        version: str = "latest",
    ) -> str:
        """Generate PowerShell installation script for Windows.

        Args:
            api_url: Base API URL for downloads.
            source: Storage source for binaries.
            version: Version to install.

        Returns:
            PowerShell script content.
        """
        source_value = source.value
        return f'''#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Hydra Agent Installer for Windows (API wrapper)
    Generated by hydra-api v{self.api_version}

.DESCRIPTION
    Downloads and installs the Hydra Agent on Windows systems.

.PARAMETER Version
    Version to install (default: latest)

.PARAMETER InstallDir
    Installation directory (default: C:\\Program Files\\Hydra)

.PARAMETER RegisterToken
    Optional registration token for auto-registration

.PARAMETER CreateAlias
    Create 'hydra' alias for hydra-agent

.EXAMPLE
    iwr -useb {api_url}/agent/install | iex

.EXAMPLE
    iwr -useb "{api_url}/agent/install?version=0.3.1" | iex
#>

param(
    [string]$Version = "{version}",
    [string]$InstallDir = "$env:ProgramFiles\\Hydra",
    [string]$RegisterToken = "",
    [switch]$CreateAlias
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$ApiUrl = "{api_url}"
$Source = "{source_value}"

function Write-Info {{ param([string]$Message) Write-Host "[INFO] $Message" -ForegroundColor Blue }}
function Write-Success {{ param([string]$Message) Write-Host "[OK] $Message" -ForegroundColor Green }}
function Write-Warn {{ param([string]$Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }}
function Write-Err {{ param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }}

function Test-Administrator {{
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}}

if (-not (Test-Administrator)) {{
    Write-Err "This script requires Administrator privileges."
    Write-Err "Please run PowerShell as Administrator and try again."
    exit 1
}}

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "   Hydra Agent Installer (Windows)"
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Create directories
Write-Info "Creating directories..."
$ConfigDir = "C:\\ProgramData\\Hydra"
$VaultDir = "C:\\ProgramData\\Hydra\\vault"
$LogDir = "C:\\ProgramData\\Hydra\\logs"

foreach ($dir in @($InstallDir, $ConfigDir, $VaultDir, $LogDir)) {{
    if (-not (Test-Path $dir)) {{
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }}
}}

# Set secure permissions on vault directory
Write-Info "Setting secure permissions on vault..."
$acl = Get-Acl $VaultDir
$acl.SetAccessRuleProtection($true, $false)
$adminRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
)
$systemRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
)
$acl.AddAccessRule($adminRule)
$acl.AddAccessRule($systemRule)
Set-Acl -Path $VaultDir -AclObject $acl

# Download binary
$DownloadUrl = "$ApiUrl/agent/download?source=binary&target=windows-amd64&version=$Version"
$BinaryPath = "$InstallDir\\hydra-agent.exe"

Write-Info "Downloading hydra-agent (version: $Version)..."
try {{
    Invoke-WebRequest -Uri $DownloadUrl -OutFile $BinaryPath -UseBasicParsing
    Write-Success "Downloaded hydra-agent.exe"
}} catch {{
    Write-Err "Failed to download binary: $_"
    exit 1
}}

# Create alias if requested
if ($CreateAlias) {{
    $AliasPath = "$InstallDir\\hydra.exe"
    if (Test-Path $AliasPath) {{ Remove-Item $AliasPath -Force }}
    Copy-Item $BinaryPath $AliasPath
    Write-Info "Created alias: hydra.exe"
}}

# Add to PATH if not already present
$EnvPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
if ($EnvPath -notlike "*$InstallDir*") {{
    Write-Info "Adding to system PATH..."
    [Environment]::SetEnvironmentVariable("Path", "$EnvPath;$InstallDir", "Machine")
    $env:Path = "$env:Path;$InstallDir"
    Write-Success "Added to PATH"
}}

# Create default config if not exists
$ConfigFile = "$ConfigDir\\agent.toml"
if (-not (Test-Path $ConfigFile)) {{
    Write-Info "Creating default configuration..."
    @"
# Hydra Agent Configuration
# Edit this file to configure the agent

[node]
node_id = "CHANGE_ME"
class = "compute"
node_type = "physical"

[api]
url = "$ApiUrl"
timeout_seconds = 30
retries = 3

[collection]
level = "neutral"
include_packages = true
include_users = true

[schedule]
enabled = true
interval_seconds = 21600
on_startup = true
"@ | Set-Content -Path $ConfigFile -Encoding UTF8
    Write-Success "Created config at $ConfigFile"
}}

# Register with token if provided
if ($RegisterToken) {{
    Write-Info "Registering with provided token..."
    & "$BinaryPath" register --token $RegisterToken
}}

Write-Host ""
Write-Success "Installation complete!"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Edit config: $ConfigFile"
Write-Host "  2. Login: hydra-agent login -u <username>"
Write-Host "  3. Register: hydra-agent register"
Write-Host "  4. Register node: hydra-agent node register"
Write-Host "  5. Install service: hydra-agent service install"
Write-Host ""
'''


# Module-level instance for convenience
_install_service: InstallScriptService | None = None


def get_install_service() -> InstallScriptService:
    """Get or create the install script service singleton.

    Returns:
        InstallScriptService instance.
    """
    global _install_service
    if _install_service is None:
        _install_service = InstallScriptService()
    return _install_service
