"""Built-in command definitions for the command registry.

These 17 commands are seeded into the command_definitions collection on startup.
They match the spec in Phase 2 Technical Specification §4.2.2 and §5 (Controls).
"""

from datetime import UTC, datetime

_NOW = datetime.now(UTC)

BUILTIN_COMMANDS: list[dict] = [
    # ── Service commands (7) ─────────────────────────────────────────────
    {
        "registryId": "reg::service::start",
        "category": "service",
        "action": "start",
        "displayName": "Start Service",
        "description": "Start a stopped service",
        "targetSchema": {"required": ["nodeId", "serviceId"]},
        "parametersSchema": None,
        "execution": {
            "runtimes": {
                "systemd": "systemctl start {service}",
                "docker": "docker start {container}",
            },
            "handler": None,
            "timeout": 30,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "medium",
            "controlPermission": "services:control:start",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::service::stop",
        "category": "service",
        "action": "stop",
        "displayName": "Stop Service",
        "description": "Stop a running service",
        "targetSchema": {"required": ["nodeId", "serviceId"]},
        "parametersSchema": None,
        "execution": {
            "runtimes": {
                "systemd": "systemctl stop {service}",
                "docker": "docker stop {container}",
            },
            "handler": None,
            "timeout": 30,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "medium",
            "controlPermission": "services:control:stop",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::service::restart",
        "category": "service",
        "action": "restart",
        "displayName": "Restart Service",
        "description": "Restart a service",
        "targetSchema": {"required": ["nodeId", "serviceId"]},
        "parametersSchema": None,
        "execution": {
            "runtimes": {
                "systemd": "systemctl restart {service}",
                "docker": "docker restart {container}",
            },
            "handler": None,
            "timeout": 60,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "medium",
            "controlPermission": "services:control:restart",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::service::reload",
        "category": "service",
        "action": "reload",
        "displayName": "Reload Service",
        "description": "Reload service configuration",
        "targetSchema": {"required": ["nodeId", "serviceId"]},
        "parametersSchema": None,
        "execution": {
            "runtimes": {
                "systemd": "systemctl reload {service}",
            },
            "handler": None,
            "timeout": 30,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "medium",
            "controlPermission": "services:control:reload",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::service::logs",
        "category": "service",
        "action": "logs",
        "displayName": "Service Logs",
        "description": "Retrieve service logs",
        "targetSchema": {"required": ["nodeId", "serviceId"]},
        "parametersSchema": {
            "properties": {
                "lines": {"type": "integer", "default": 100, "description": "Number of log lines"},
                "since": {"type": "string", "description": "Time filter (e.g. '1h', '30m')"},
            }
        },
        "execution": {
            "runtimes": {
                "systemd": "journalctl -u {service} -n {lines}",
                "docker": "docker logs --tail {lines} {container}",
            },
            "handler": None,
            "timeout": 30,
            "deliveryMode": "direct_or_poll",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "safe",
            "controlPermission": "services:control:logs",
        },
        "audit": {"logLevel": "minimal", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::service::inspect",
        "category": "service",
        "action": "inspect",
        "displayName": "Inspect Service",
        "description": "Get detailed service info",
        "targetSchema": {"required": ["nodeId", "serviceId"]},
        "parametersSchema": None,
        "execution": {
            "runtimes": {
                "systemd": "systemctl show {service}",
                "docker": "docker inspect {container}",
            },
            "handler": None,
            "timeout": 15,
            "deliveryMode": "direct_or_poll",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "safe",
            "controlPermission": "services:control:inspect",
        },
        "audit": {"logLevel": "minimal", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::service::update",
        "category": "service",
        "action": "update",
        "displayName": "Update Service",
        "description": "Update service (pull new image, etc.)",
        "targetSchema": {"required": ["nodeId", "serviceId"]},
        "parametersSchema": {
            "properties": {
                "version": {"type": "string", "description": "Target version (optional)"},
            }
        },
        "execution": {
            "runtimes": {
                "docker": "docker pull {image} && docker restart {container}",
            },
            "handler": None,
            "timeout": 300,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "admin",
            "requiresConfirmation": True,
            "confirmationMessage": "This will update the service which may cause downtime.",
            "dangerLevel": "high",
            "controlPermission": "services:control:update",
        },
        "audit": {"logLevel": "verbose", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    # ── Node commands (4) ────────────────────────────────────────────────
    {
        "registryId": "reg::node::reboot",
        "category": "node",
        "action": "reboot",
        "displayName": "Reboot Node",
        "description": "Reboot the node",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": None,
        "execution": {
            "handler": "node_reboot",
            "timeout": 300,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "admin",
            "requiresConfirmation": True,
            "confirmationMessage": "This will reboot the node. All running services will be interrupted.",
            "dangerLevel": "high",
            "controlPermission": "nodes:control:reboot",
        },
        "audit": {"logLevel": "verbose", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::node::shutdown",
        "category": "node",
        "action": "shutdown",
        "displayName": "Shutdown Node",
        "description": "Shutdown the node",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": None,
        "execution": {
            "handler": "node_shutdown",
            "timeout": 300,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "admin",
            "requiresConfirmation": True,
            "confirmationMessage": "This will shut down the node. Manual intervention required to restart.",
            "dangerLevel": "critical",
            "controlPermission": "nodes:control:shutdown",
        },
        "audit": {"logLevel": "verbose", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::node::update-system",
        "category": "node",
        "action": "update-system",
        "displayName": "Update System",
        "description": "Run system updates",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": None,
        "execution": {
            "handler": "node_update_system",
            "timeout": 1800,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "admin",
            "requiresConfirmation": True,
            "confirmationMessage": "This will run system package updates on the node.",
            "dangerLevel": "critical",
            "controlPermission": "nodes:control:update-system",
        },
        "audit": {"logLevel": "verbose", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::node::set-hostname",
        "category": "node",
        "action": "set-hostname",
        "displayName": "Set Hostname",
        "description": "Change node hostname",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": {
            "required": ["hostname"],
            "properties": {
                "hostname": {"type": "string", "maxLength": 64, "description": "New hostname"},
            },
        },
        "execution": {
            "handler": "node_set_hostname",
            "timeout": 30,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "admin",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "medium",
            "controlPermission": "nodes:control:set-hostname",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    # ── Agent commands (6) ───────────────────────────────────────────────
    {
        "registryId": "reg::agent::restart",
        "category": "agent",
        "action": "restart",
        "displayName": "Restart Agent",
        "description": "Restart the Hydra agent",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": None,
        "execution": {
            "handler": "agent_restart",
            "timeout": 30,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "admin",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "high",
            "controlPermission": "agent:control:restart",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::agent::update",
        "category": "agent",
        "action": "update",
        "displayName": "Update Agent",
        "description": "Update agent to new version",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": {
            "properties": {
                "version": {"type": "string", "description": "Target version"},
                "source": {"type": "string", "description": "Upgrade source (default: binary)"},
            }
        },
        "execution": {
            "handler": "agent_update",
            "timeout": 180,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "admin",
            "requiresConfirmation": True,
            "confirmationMessage": "This will update the Hydra agent binary on the node.",
            "dangerLevel": "high",
            "controlPermission": "agent:control:update",
        },
        "audit": {"logLevel": "verbose", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::agent::config-reload",
        "category": "agent",
        "action": "config-reload",
        "displayName": "Reload Config",
        "description": "Reload agent configuration",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": None,
        "execution": {
            "handler": "agent_config_reload",
            "timeout": 15,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "medium",
            "controlPermission": "agent:control:config-reload",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::agent::collect-now",
        "category": "agent",
        "action": "collect-now",
        "displayName": "Collect Now",
        "description": "Trigger immediate profile collection",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": None,
        "execution": {
            "handler": "agent_collect_now",
            "timeout": 60,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "safe",
            "controlPermission": "agent:control:collect-now",
        },
        "audit": {"logLevel": "minimal", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::agent::probe-network",
        "category": "agent",
        "action": "probe-network",
        "displayName": "Probe Network",
        "description": "Run network discovery scan",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": {
            "properties": {
                "subnet": {"type": "string", "description": "Subnet to scan (CIDR notation)"},
                "targets": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "One or more CIDR targets to probe",
                },
                "options": {
                    "type": "object",
                    "description": "Optional probe tuning such as timeoutMs",
                },
            }
        },
        "execution": {
            "handler": "agent_probe_network",
            "timeout": 120,
            "deliveryMode": "poll_only",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "operator",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "low",
            "controlPermission": "agent:control:probe-network",
        },
        "audit": {"logLevel": "standard", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
    {
        "registryId": "reg::agent::status",
        "category": "agent",
        "action": "status",
        "displayName": "Agent Status",
        "description": "Get agent status",
        "targetSchema": {"required": ["nodeId"]},
        "parametersSchema": None,
        "execution": {
            "handler": "agent_status",
            "timeout": 10,
            "deliveryMode": "direct_or_poll",
            "retryable": False,
            "maxRetries": 0,
        },
        "rbac": {
            "minimumRole": "viewer",
            "requiresConfirmation": False,
            "confirmationMessage": None,
            "dangerLevel": "safe",
            "controlPermission": "agent:control:status",
        },
        "audit": {"logLevel": "minimal", "captureOutput": True, "sensitiveParameters": []},
        "metadata": {"version": "0.5.0", "addedAt": _NOW, "builtIn": True, "deprecated": False},
    },
]
