"""Agent installation endpoints for curl-based deployments."""

import re
from pathlib import Path
from typing import Literal

import structlog
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import Response, StreamingResponse

from hydra.v1 import __version__
from hydra.core.config import get_settings
from hydra.v1.core.deps import StorageServiceDep

router = APIRouter(prefix="/agent", tags=["Agent Distribution"])
logger = structlog.get_logger(__name__)

# Version validation pattern (security: prevent path traversal)
VERSION_PATTERN = re.compile(r'^[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9]+)?$|^latest$')

# Supported targets for binary downloads
SUPPORTED_TARGETS = {
    "hydra-agent-linux-amd64": {"os": "linux", "arch": "amd64", "target": "linux-amd64"},
    "hydra-agent-linux-arm64": {"os": "linux", "arch": "arm64", "target": "linux-arm64"},
    "hydra-agent-linux-armv7": {"os": "linux", "arch": "armv7", "target": "linux-armv7"},
    "hydra-agent-darwin-amd64": {"os": "darwin", "arch": "amd64", "target": "darwin-amd64"},
    "hydra-agent-darwin-arm64": {"os": "darwin", "arch": "arm64", "target": "darwin-arm64"},
    "hydra-agent-freebsd-amd64": {"os": "freebsd", "arch": "amd64", "target": "freebsd-amd64"},
}


def validate_version(version: str) -> str:
    """Validate version parameter to prevent path traversal."""
    if not VERSION_PATTERN.match(version):
        raise HTTPException(
            status_code=400,
            detail={
                "error": {
                    "code": "INVALID_VERSION",
                    "message": f"Invalid version format: '{version}'",
                    "details": {"pattern": "X.Y.Z or X.Y.Z-suffix or latest"},
                }
            },
        )
    return version


def get_installation_script(api_url: str, settings) -> str:
    """Generate the bash installation script with embedded API URL."""
    return f'''#!/bin/bash
#
# Hydra Agent Installer
# Generated by hydra-api v{__version__}
#
# Usage:
#   curl -sSL {api_url}/install | bash -s -- [OPTIONS]
#
# Authentication (one required for registration):
#   --username        User account for registration
#   --password        User password
#   --token           Node registration token (alternative to user/pass)
#
# Options:
#   --api-url         API base URL (default: derived from script source)
#   --node-id         Node identifier (default: hostname)
#   --node-class      compute|networking|iot (default: compute)
#   --node-type       physical|logical (default: auto-detect)
#   --node-kind       Specific kind (default: auto-detect)
#   --display-name    Human-readable name (default: hostname)
#   --parent-node     Parent node ID for logical nodes
#   --tags            Comma-separated tags
#   --collection-level shallow|neutral|deep (default: neutral)
#   --cron            Collection schedule (default: "0 */6 * * *")
#   --install-dir     Binary location (default: /usr/local/bin)
#   --config-dir      Config location (default: /etc/hydra)
#   --no-systemd      Skip systemd service setup
#   --no-start        Don\'t start service after install
#   --no-register     Skip node registration
#   --verify-ssl      Verify TLS certs (default: true)
#   --dry-run         Preview actions without executing
#   --unattended      Skip all prompts
#   --help            Show this help
#
set -euo pipefail

# Configuration defaults
API_URL="${{HYDRA_API_URL:-{api_url}}}"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/hydra"
LOG_DIR="/var/log/hydra"
COLLECTION_LEVEL="neutral"
CRON_SCHEDULE="0 */6 * * *"
VERIFY_SSL="true"
NO_SYSTEMD="false"
NO_START="false"
NO_REGISTER="false"
DRY_RUN="false"
UNATTENDED="false"

# Node defaults
NODE_ID=""
NODE_CLASS="compute"
NODE_TYPE=""
NODE_KIND=""
DISPLAY_NAME=""
PARENT_NODE=""
TAGS=""

# Auth
USERNAME=""
PASSWORD=""
TOKEN=""

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

info()    {{ echo -e "${{BLUE}}[INFO]${{NC}} $*"; }}
warn()    {{ echo -e "${{YELLOW}}[WARN]${{NC}} $*"; }}
error()   {{ echo -e "${{RED}}[ERROR]${{NC}} $*" >&2; }}
success() {{ echo -e "${{GREEN}}[OK]${{NC}} $*"; }}

show_help() {{
    head -50 "$0" | grep -E "^#" | tail -n +3 | sed 's/^# *//'
    exit 0
}}

parse_args() {{
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help|-h) show_help ;;
            --api-url) API_URL="$2"; shift 2 ;;
            --node-id) NODE_ID="$2"; shift 2 ;;
            --node-class) NODE_CLASS="$2"; shift 2 ;;
            --node-type) NODE_TYPE="$2"; shift 2 ;;
            --node-kind) NODE_KIND="$2"; shift 2 ;;
            --display-name) DISPLAY_NAME="$2"; shift 2 ;;
            --parent-node) PARENT_NODE="$2"; shift 2 ;;
            --tags) TAGS="$2"; shift 2 ;;
            --collection-level) COLLECTION_LEVEL="$2"; shift 2 ;;
            --cron) CRON_SCHEDULE="$2"; shift 2 ;;
            --install-dir) INSTALL_DIR="$2"; shift 2 ;;
            --config-dir) CONFIG_DIR="$2"; shift 2 ;;
            --username|-u) USERNAME="$2"; shift 2 ;;
            --password|-p) PASSWORD="$2"; shift 2 ;;
            --token) TOKEN="$2"; shift 2 ;;
            --no-systemd) NO_SYSTEMD="true"; shift ;;
            --no-start) NO_START="true"; shift ;;
            --no-register) NO_REGISTER="true"; shift ;;
            --verify-ssl) VERIFY_SSL="$2"; shift 2 ;;
            --dry-run) DRY_RUN="true"; shift ;;
            --unattended) UNATTENDED="true"; shift ;;
            *) error "Unknown option: $1"; exit 1 ;;
        esac
    done
}}

check_root() {{
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (use sudo)"
        exit 1
    fi
}}

detect_os() {{
    local os
    os=$(uname -s | tr '[:upper:]' '[:lower:]')
    case "$os" in
        linux)   echo "linux" ;;
        darwin)  echo "darwin" ;;
        freebsd) echo "freebsd" ;;
        mingw*|msys*|cygwin*) echo "windows" ;;
        *) error "Unsupported OS: $os"; exit 1 ;;
    esac
}}

detect_arch() {{
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64|amd64)  echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        armv7l|armhf)  echo "armv7" ;;
        *) error "Unsupported architecture: $arch"; exit 1 ;;
    esac
}}

detect_init_system() {{
    if command -v systemctl &> /dev/null && [[ -d /run/systemd/system ]]; then
        echo "systemd"
    elif command -v rc-service &> /dev/null; then
        echo "openrc"
    elif [[ "$(uname -s)" == "Darwin" ]]; then
        echo "launchd"
    else
        echo "none"
    fi
}}

detect_virtualization() {{
    # Try systemd-detect-virt first
    if command -v systemd-detect-virt &> /dev/null; then
        local virt
        virt=$(systemd-detect-virt 2>/dev/null || echo "none")
        case "$virt" in
            none) echo "bare-metal" ;;
            kvm|qemu|vmware|oracle|xen|microsoft) echo "vm" ;;
            lxc|lxc-libvirt) echo "lxc" ;;
            docker) echo "docker" ;;
            podman) echo "podman" ;;
            *) echo "vm" ;;
        esac
        return
    fi

    # Check for container markers
    if [[ -f /.dockerenv ]]; then
        echo "docker"
        return
    fi

    if grep -q "container=lxc" /proc/1/environ 2>/dev/null; then
        echo "lxc"
        return
    fi

    # Default to bare-metal
    echo "bare-metal"
}}

check_network() {{
    info "Checking network connectivity..."
    local curl_opts="-sSL --connect-timeout 10"
    [[ "$VERIFY_SSL" != "true" ]] && curl_opts="$curl_opts -k"

    if ! curl $curl_opts "${{API_URL}}/health" > /dev/null 2>&1; then
        error "Cannot reach Hydra API at ${{API_URL}}"
        exit 1
    fi
    success "Network connectivity OK"
}}

check_existing() {{
    if [[ -f "${{INSTALL_DIR}}/hydra-agent" ]]; then
        local version
        version=$("${{INSTALL_DIR}}/hydra-agent" --version 2>/dev/null | head -1 || echo "unknown")
        warn "Existing installation found: $version"
        if [[ "$UNATTENDED" != "true" ]]; then
            read -p "Overwrite? [y/N] " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                info "Installation cancelled"
                exit 0
            fi
        fi
    fi
}}

download_agent() {{
    local os arch binary_name download_url checksum_url
    os=$(detect_os)
    arch=$(detect_arch)
    binary_name="hydra-agent-${{os}}-${{arch}}"
    download_url="${{API_URL}}/install/${{binary_name}}"
    checksum_url="${{download_url}}.sha256"

    info "Downloading ${{binary_name}}..."

    local curl_opts="-sSL"
    [[ "$VERIFY_SSL" != "true" ]] && curl_opts="$curl_opts -k"

    TMP_DIR=$(mktemp -d)
    trap "rm -rf $TMP_DIR" EXIT

    if [[ "$DRY_RUN" == "true" ]]; then
        info "[DRY RUN] Would download: $download_url"
        return
    fi

    curl $curl_opts -o "${{TMP_DIR}}/hydra-agent" "$download_url" || {{
        error "Failed to download agent binary"
        exit 1
    }}

    # Try to download checksum
    if curl $curl_opts -o "${{TMP_DIR}}/hydra-agent.sha256" "$checksum_url" 2>/dev/null; then
        info "Verifying checksum..."
        cd "$TMP_DIR"
        if command -v sha256sum &> /dev/null; then
            echo "$(cat hydra-agent.sha256)  hydra-agent" | sha256sum -c - || {{
                error "Checksum verification failed!"
                exit 1
            }}
        elif command -v shasum &> /dev/null; then
            echo "$(cat hydra-agent.sha256)  hydra-agent" | shasum -a 256 -c - || {{
                error "Checksum verification failed!"
                exit 1
            }}
        fi
        cd - > /dev/null
        success "Checksum verified"
    else
        warn "Checksum file not available, skipping verification"
    fi

    # Install binary
    info "Installing to ${{INSTALL_DIR}}/hydra-agent..."
    install -m 755 "${{TMP_DIR}}/hydra-agent" "${{INSTALL_DIR}}/hydra-agent"
    success "Binary installed"
}}

authenticate() {{
    if [[ -n "$TOKEN" ]]; then
        # Use registration token
        AUTH_HEADER="X-Registration-Token: $TOKEN"
        info "Using registration token for authentication"
        return
    fi

    if [[ -z "$USERNAME" ]]; then
        if [[ "$UNATTENDED" == "true" ]]; then
            error "No authentication method provided (--username or --token required)"
            exit 1
        fi
        read -p "Username: " USERNAME
    fi

    if [[ -z "$PASSWORD" ]]; then
        if [[ "$UNATTENDED" == "true" ]]; then
            error "Password required for user authentication"
            exit 1
        fi
        read -s -p "Password: " PASSWORD
        echo
    fi

    info "Authenticating as $USERNAME..."

    local curl_opts="-sSL"
    [[ "$VERIFY_SSL" != "true" ]] && curl_opts="$curl_opts -k"

    local auth_response
    auth_response=$(curl $curl_opts -X POST "${{API_URL}}/auth/login" \\
        -H "Content-Type: application/json" \\
        -d "{{\\"username\\":\\"$USERNAME\\",\\"password\\":\\"$PASSWORD\\"}}" 2>&1)

    local access_token
    access_token=$(echo "$auth_response" | grep -o '"accessToken":"[^"]*"' | cut -d'"' -f4)

    if [[ -z "$access_token" ]]; then
        error "Authentication failed"
        echo "$auth_response" | grep -o '"message":"[^"]*"' | cut -d'"' -f4
        exit 1
    fi

    AUTH_HEADER="Authorization: Bearer $access_token"
    success "Authentication successful"
}}

register_node() {{
    if [[ "$NO_REGISTER" == "true" ]]; then
        info "Skipping node registration (--no-register)"
        return
    fi

    # Set defaults
    [[ -z "$NODE_ID" ]] && NODE_ID=$(hostname | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9.-')
    [[ -z "$DISPLAY_NAME" ]] && DISPLAY_NAME=$(hostname)

    # Auto-detect node type if not specified
    if [[ -z "$NODE_TYPE" ]]; then
        local virt
        virt=$(detect_virtualization)
        case "$virt" in
            bare-metal) NODE_TYPE="physical" ;;
            *) NODE_TYPE="logical" ;;
        esac
    fi

    # Auto-detect node kind if not specified
    if [[ -z "$NODE_KIND" ]]; then
        NODE_KIND=$(detect_virtualization)
    fi

    info "Registering node: $NODE_ID"

    local curl_opts="-sSL"
    [[ "$VERIFY_SSL" != "true" ]] && curl_opts="$curl_opts -k"

    # Build tags JSON array
    local tags_json="[]"
    if [[ -n "$TAGS" ]]; then
        tags_json=$(echo "$TAGS" | tr ',' '\\n' | sed 's/^/"/;s/$/"/' | tr '\\n' ',' | sed 's/,$//' | sed 's/^/[/;s/$/]/')
    fi

    # Build request body
    local request_body
    request_body=$(cat <<JSONEOF
{{
    "nodeId": "$NODE_ID",
    "class": "$NODE_CLASS",
    "type": "$NODE_TYPE",
    "kind": "$NODE_KIND",
    "displayName": "$DISPLAY_NAME",
    "tags": $tags_json
JSONEOF
)

    # Add optional parent node
    if [[ -n "$PARENT_NODE" ]]; then
        request_body=$(echo "$request_body" | sed 's/$/,/')
        request_body="$request_body
    \\"parentNodeId\\": \\"$PARENT_NODE\\""
    fi

    request_body="$request_body
}}"

    if [[ "$DRY_RUN" == "true" ]]; then
        info "[DRY RUN] Would register node: $NODE_ID"
        info "[DRY RUN] Class: $NODE_CLASS, Type: $NODE_TYPE, Kind: $NODE_KIND"
        return
    fi

    local register_response
    register_response=$(curl $curl_opts -X POST "${{API_URL}}/node/register" \\
        -H "$AUTH_HEADER" \\
        -H "Content-Type: application/json" \\
        -d "$request_body" 2>&1)

    local api_key
    api_key=$(echo "$register_response" | grep -o '"apiKey":"[^"]*"' | cut -d'"' -f4)
    local api_key_id
    api_key_id=$(echo "$register_response" | grep -o '"apiKeyId":"[^"]*"' | cut -d'"' -f4)

    if [[ -z "$api_key" ]]; then
        error "Node registration failed"
        echo "$register_response" | grep -o '"message":"[^"]*"' | cut -d'"' -f4
        exit 1
    fi

    # Save credentials
    mkdir -p "$CONFIG_DIR"
    cat > "${{CONFIG_DIR}}/credentials.json" <<EOF
{{
    "nodeId": "$NODE_ID",
    "apiKey": "$api_key",
    "apiKeyId": "$api_key_id",
    "registeredAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}}
EOF
    chmod 600 "${{CONFIG_DIR}}/credentials.json"

    success "Node registered: $NODE_ID"
}}

generate_config() {{
    info "Generating configuration..."

    if [[ "$DRY_RUN" == "true" ]]; then
        info "[DRY RUN] Would generate config at ${{CONFIG_DIR}}/agent.toml"
        return
    fi

    mkdir -p "$CONFIG_DIR" "$LOG_DIR"

    cat > "${{CONFIG_DIR}}/agent.toml" <<EOF
# Hydra Agent Configuration
# Generated by hydra-agent installer

[node]
node_id = "$NODE_ID"
class = "$NODE_CLASS"
type = "$NODE_TYPE"
kind = "$NODE_KIND"
display_name = "$DISPLAY_NAME"

[api]
url = "$API_URL"
credentials_file = "$CONFIG_DIR/credentials.json"
timeout_seconds = 30
retries = 3
verify_ssl = $VERIFY_SSL

[schedule]
cron = "$CRON_SCHEDULE"
events = ["boot", "network_change", "package_change"]

[collection]
level = "$COLLECTION_LEVEL"

[collectors]
hardware = true
network = true
storage = true
software = true
services = true

[logging]
level = "info"
format = "json"
file = "$LOG_DIR/agent.log"
EOF

    chmod 644 "${{CONFIG_DIR}}/agent.toml"
    success "Configuration generated"
}}

install_systemd_service() {{
    if [[ "$NO_SYSTEMD" == "true" ]]; then
        info "Skipping systemd service (--no-systemd)"
        return
    fi

    local init_system
    init_system=$(detect_init_system)

    if [[ "$init_system" != "systemd" ]]; then
        warn "systemd not detected, skipping service installation"
        return
    fi

    info "Installing systemd service..."

    if [[ "$DRY_RUN" == "true" ]]; then
        info "[DRY RUN] Would create /etc/systemd/system/hydra-agent.service"
        return
    fi

    cat > /etc/systemd/system/hydra-agent.service <<EOF
[Unit]
Description=Hydra Infrastructure Agent
Documentation=https://github.com/yourorg/hydra
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/hydra-agent run
Restart=on-failure
RestartSec=10
User=root
Environment=HYDRA_CONFIG=/etc/hydra/agent.toml

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=/var/log/hydra /etc/hydra

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable hydra-agent.service
    success "systemd service installed and enabled"

    if [[ "$NO_START" != "true" ]]; then
        info "Starting hydra-agent service..."
        systemctl start hydra-agent.service
        sleep 2
        if systemctl is-active --quiet hydra-agent.service; then
            success "Service started successfully"
        else
            warn "Service may have failed to start. Check: journalctl -u hydra-agent"
        fi
    fi
}}

main() {{
    parse_args "$@"

    echo ""
    echo "=========================================="
    echo "     Hydra Agent Installer v{__version__}"
    echo "=========================================="
    echo ""

    if [[ "$DRY_RUN" == "true" ]]; then
        info "Running in DRY RUN mode - no changes will be made"
        echo ""
    fi

    check_root
    check_network
    check_existing
    download_agent

    if [[ "$NO_REGISTER" != "true" ]]; then
        authenticate
        register_node
    fi

    generate_config
    install_systemd_service

    echo ""
    success "=========================================="
    success "     Installation Complete!"
    success "=========================================="
    echo ""
    info "Node ID:     $NODE_ID"
    info "Config:      ${{CONFIG_DIR}}/agent.toml"
    info "Credentials: ${{CONFIG_DIR}}/credentials.json"
    echo ""

    if [[ "$NO_SYSTEMD" != "true" ]] && [[ "$(detect_init_system)" == "systemd" ]]; then
        info "Service status: $(systemctl is-active hydra-agent 2>/dev/null || echo 'not running')"
        info "View logs: journalctl -u hydra-agent -f"
    else
        info "To run manually: hydra-agent --config ${{CONFIG_DIR}}/agent.toml"
    fi
    echo ""
}}

main "$@"
'''


@router.get(
    "/install",
    summary="Installation Script",
    description="Returns a bash installation script for curl-based agent deployment.",
    response_class=Response,
    responses={
        200: {
            "description": "Installation script",
            "content": {"text/x-shellscript": {}},
        }
    },
)
async def get_install_script(
    request: Request,
    arch: Literal["amd64", "arm64", "armv7"] | None = Query(
        default=None, description="Target architecture (auto-detect if not specified)"
    ),
    os: Literal["linux", "darwin", "freebsd"] | None = Query(
        default=None, description="Target OS (auto-detect if not specified)"
    ),
    version: str = Query(default="latest", description="Agent version to install"),
) -> Response:
    """
    Generate and return the installation script.

    The script can be executed via curl:

    ```bash
    curl -sSL https://hydra.local/api/v1/install | bash -s -- --username admin --password ***
    ```
    """
    # Determine API URL from request
    api_url = str(request.base_url).rstrip("/")
    if request.url.path.startswith("/api/v1"):
        api_url = f"{api_url.rsplit('/api/v1', 1)[0]}/api/v1"
    else:
        api_url = f"{api_url}/api/v1"

    settings = get_settings()
    script = get_installation_script(api_url, settings)

    logger.info(
        "install_script_generated",
        api_url=api_url,
        requested_arch=arch,
        requested_os=os,
        version=version,
    )

    return Response(
        content=script,
        media_type="text/x-shellscript",
        headers={
            "Content-Disposition": 'attachment; filename="hydra-install.sh"',
            "X-Hydra-Version": __version__,
        },
    )


@router.get(
    "/download/{binary}",
    summary="Download Agent Binary",
    description="Download a specific agent binary for manual installation.",
    response_class=Response,
    response_model=None,
    responses={
        200: {
            "description": "Agent binary file",
            "content": {"application/octet-stream": {}},
        },
        404: {"description": "Binary not found"},
    },
)
async def download_binary(
    binary: str,
    storage: StorageServiceDep,
    version: str = Query(default="latest", description="Agent version"),
) -> Response:
    """
    Download a specific agent binary.

    Available binaries:
    - hydra-agent-linux-amd64
    - hydra-agent-linux-arm64
    - hydra-agent-linux-armv7
    - hydra-agent-darwin-amd64
    - hydra-agent-darwin-arm64
    - hydra-agent-freebsd-amd64

    Also supports .sha256 suffix for checksum files.

    Binary retrieval priority:
    1. Object storage (S3/Garage) if configured
    2. Local filesystem fallback
    """
    from hydra.v1.services.storage import ObjectNotFoundError, StorageUnavailableError

    # Validate version (security: prevent path traversal)
    version = validate_version(version)

    # Handle checksum request
    is_checksum = binary.endswith(".sha256")
    actual_binary = binary.removesuffix(".sha256")

    if actual_binary not in SUPPORTED_TARGETS:
        raise HTTPException(
            status_code=404,
            detail={
                "error": {
                    "code": "BINARY_NOT_FOUND",
                    "message": f"Binary '{actual_binary}' not found",
                    "details": {"available": list(SUPPORTED_TARGETS.keys())},
                }
            },
        )

    target = SUPPORTED_TARGETS[actual_binary]["target"]

    try:
        # Resolve 'latest' to actual version
        resolved_version = version
        if version == "latest":
            resolved_version = await storage.get_latest_version(target)
            if not resolved_version:
                raise HTTPException(
                    status_code=404,
                    detail={
                        "error": {
                            "code": "NO_VERSIONS_AVAILABLE",
                            "message": f"No versions available for {actual_binary}",
                        }
                    },
                )

        # Build the storage key
        object_key = f"agents/{target}/{resolved_version}/hydra-agent"

        if is_checksum:
            # Get checksum from metadata
            try:
                metadata = await storage.get_object_metadata(object_key)
                checksum = metadata.get("sha256", "")
                if not checksum:
                    # Try to get checksum file
                    checksum_key = f"{object_key}.sha256"
                    if await storage.object_exists(checksum_key):
                        async for chunk in storage.get_object_stream(checksum_key):
                            checksum = chunk.decode("utf-8").strip().split()[0]
                            break

                return Response(
                    content=f"{checksum}  {actual_binary}\n",
                    media_type="text/plain",
                    headers={
                        "Content-Disposition": f'attachment; filename="{binary}"',
                        "X-Hydra-Version": resolved_version,
                    },
                )
            except ObjectNotFoundError:
                raise HTTPException(
                    status_code=404,
                    detail={
                        "error": {
                            "code": "CHECKSUM_NOT_FOUND",
                            "message": f"Checksum not available for {actual_binary} v{resolved_version}",
                        }
                    },
                )

        # Get metadata for response headers
        metadata = await storage.get_object_metadata(object_key)

        logger.info(
            "binary_download",
            binary=actual_binary,
            version=resolved_version,
            target=target,
            size=metadata.get("size"),
        )

        # Stream the binary
        async def stream_binary():
            async for chunk in storage.get_object_stream(object_key):
                yield chunk

        headers = {
            "Content-Disposition": f'attachment; filename="{actual_binary}"',
            "X-Hydra-Version": resolved_version,
        }
        if metadata.get("size"):
            headers["Content-Length"] = str(metadata["size"])
        if metadata.get("sha256"):
            headers["X-Checksum-SHA256"] = metadata["sha256"]

        return StreamingResponse(
            stream_binary(),
            media_type="application/octet-stream",
            headers=headers,
        )

    except ObjectNotFoundError:
        raise HTTPException(
            status_code=404,
            detail={
                "error": {
                    "code": "BINARY_NOT_FOUND",
                    "message": f"Binary '{actual_binary}' v{version} not found",
                    "details": {"target": target, "version": version},
                }
            },
        )
    except StorageUnavailableError as e:
        logger.error(
            "storage_unavailable",
            binary=actual_binary,
            version=version,
            error=str(e),
        )
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "STORAGE_UNAVAILABLE",
                    "message": "Binary storage is temporarily unavailable",
                }
            },
        )


@router.get(
    "/versions",
    summary="List Agent Versions",
    description="List available agent versions for all supported targets.",
    responses={
        200: {
            "description": "Version manifest",
            "content": {"application/json": {}},
        },
        503: {
            "description": "Storage not configured",
        },
    },
)
async def list_versions(
    storage: StorageServiceDep,
) -> dict:
    """
    List available agent versions.

    Returns a manifest with:
    - Latest version
    - Available versions per target
    - Size and checksum for each version

    Requires S3-compatible object storage to be configured.
    """
    from hydra.v1.services.storage import StorageUnavailableError

    # Check if storage is configured
    if storage is None:
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "STORAGE_NOT_CONFIGURED",
                    "message": "Object storage is not configured. Set HYDRA_OBJECT_STORAGE_ENABLED=true and provide S3 credentials.",
                }
            },
        )

    manifest = {
        "schemaVersion": 1,
        "latestVersion": __version__,
        "targets": {},
    }

    for target_name, target_info in SUPPORTED_TARGETS.items():
        target = target_info["target"]

        try:
            logger.debug("listing_versions_for_target", target=target)

            # Get versions from storage
            versions = await storage.list_versions(target)
            latest = await storage.get_latest_version(target)

            logger.debug(
                "versions_found",
                target=target,
                version_count=len(versions),
                latest=latest,
            )

            if versions:
                manifest["targets"][target] = {
                    "latest": latest or (versions[0]["version"] if versions else None),
                    "versions": versions,
                }
            else:
                manifest["targets"][target] = {
                    "latest": None,
                    "versions": [],
                    "status": "no_binaries_available",
                }
        except StorageUnavailableError as e:
            logger.warning("storage_unavailable_for_target", target=target, error=str(e))
            manifest["targets"][target] = {
                "latest": None,
                "versions": [],
                "status": "storage_unavailable",
            }
        except Exception as e:
            logger.warning(
                "list_versions_error",
                target=target,
                error=str(e),
                error_type=type(e).__name__,
            )
            manifest["targets"][target] = {
                "latest": None,
                "versions": [],
                "status": "error",
                "error": str(e),
            }

    logger.info("versions_listed", target_count=len(manifest["targets"]))

    return manifest
