#!/bin/bash
#
# Hydra Data Layer Setup Script
#
# This script sets up the data layer for Hydra (MongoDB, Redis, Garage).
#
# Usage:
#   ./setup-data-layer.sh [OPTIONS]
#
# Options:
#   --bundled     Start bundled data services via Docker (default)
#   --external    Configure for external data services
#   --generate    Generate credentials only (no service start)
#   --help        Show this help
#
# Examples:
#   ./setup-data-layer.sh --bundled     # Start local MongoDB, Redis, Garage
#   ./setup-data-layer.sh --external    # Configure for external services
#   ./setup-data-layer.sh --generate    # Just generate .env file
#

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }

# Default mode
MODE="bundled"
GENERATE_ONLY="false"

show_help() {
    head -30 "$0" | grep -E "^#" | tail -n +2 | sed 's/^# *//'
    exit 0
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help|-h) show_help ;;
            --bundled) MODE="bundled"; shift ;;
            --external) MODE="external"; shift ;;
            --generate) GENERATE_ONLY="true"; shift ;;
            *) error "Unknown option: $1"; exit 1 ;;
        esac
    done
}

check_dependencies() {
    info "Checking dependencies..."

    local missing=()

    command -v docker &> /dev/null || missing+=("docker")
    command -v docker compose &> /dev/null || command -v docker-compose &> /dev/null || missing+=("docker-compose")
    command -v openssl &> /dev/null || missing+=("openssl")

    if [[ ${#missing[@]} -gt 0 ]]; then
        error "Missing dependencies: ${missing[*]}"
        error "Please install them and retry."
        exit 1
    fi

    success "All dependencies installed"
}

generate_secret() {
    openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

generate_hex_key() {
    local length=${1:-32}
    openssl rand -hex "$length"
}

generate_credentials() {
    info "Generating secure credentials..."

    # Generate secrets if not already set
    JWT_SECRET="${HYDRA_JWT_SECRET:-$(generate_secret)}"
    MONGO_ROOT_PASS="${MONGO_ROOT_PASS:-$(generate_secret)}"
    REDIS_PASSWORD="${REDIS_PASSWORD:-$(generate_secret)}"
    GARAGE_RPC_SECRET="${GARAGE_RPC_SECRET:-$(generate_hex_key 32)}"
    GARAGE_ACCESS_KEY="${HYDRA_OBJECT_STORAGE_ACCESS_KEY:-$(generate_hex_key 20)}"
    GARAGE_SECRET_KEY="${HYDRA_OBJECT_STORAGE_SECRET_KEY:-$(generate_hex_key 40)}"

    success "Credentials generated"
}

write_env_file() {
    local env_file="$PROJECT_DIR/.env"

    info "Writing configuration to $env_file..."

    cat > "$env_file" <<EOF
# Hydra Environment Configuration
# Generated by setup-data-layer.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Environment
HYDRA_ENV=production

# JWT Secret (keep this safe!)
HYDRA_JWT_SECRET=$JWT_SECRET

# MongoDB Configuration
EOF

    if [[ "$MODE" == "bundled" ]]; then
        cat >> "$env_file" <<EOF
HYDRA_MONGODB_URI=mongodb://hydra:${MONGO_ROOT_PASS}@localhost:27017/hydra?authSource=hydra
HYDRA_MONGODB_DATABASE=hydra
MONGO_ROOT_USER=hydra
MONGO_ROOT_PASS=$MONGO_ROOT_PASS

# Redis Configuration
HYDRA_REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379/0
REDIS_PASSWORD=$REDIS_PASSWORD

# Object Storage (Garage)
HYDRA_OBJECT_STORAGE_ENABLED=true
HYDRA_OBJECT_STORAGE_ENDPOINT=http://localhost:3900
HYDRA_OBJECT_STORAGE_BUCKET=hydra-bucket
HYDRA_OBJECT_STORAGE_ACCESS_KEY=$GARAGE_ACCESS_KEY
HYDRA_OBJECT_STORAGE_SECRET_KEY=$GARAGE_SECRET_KEY
HYDRA_OBJECT_STORAGE_REGION=garage
GARAGE_RPC_SECRET=$GARAGE_RPC_SECRET
EOF
    else
        cat >> "$env_file" <<EOF
# Configure these for your external MongoDB instance
HYDRA_MONGODB_URI=mongodb://user:password@your-mongodb-host:27017/hydra?authSource=admin
HYDRA_MONGODB_DATABASE=hydra

# Configure for your external Redis instance
HYDRA_REDIS_URL=redis://:password@your-redis-host:6379/0

# Object Storage (optional - configure if using external S3/Garage)
HYDRA_OBJECT_STORAGE_ENABLED=false
# HYDRA_OBJECT_STORAGE_ENDPOINT=https://your-s3-endpoint
# HYDRA_OBJECT_STORAGE_BUCKET=hydra-bucket
# HYDRA_OBJECT_STORAGE_ACCESS_KEY=your-access-key
# HYDRA_OBJECT_STORAGE_SECRET_KEY=your-secret-key
# HYDRA_OBJECT_STORAGE_REGION=us-east-1
EOF
    fi

    cat >> "$env_file" <<EOF

# SMTP Configuration (optional - for password reset emails)
HYDRA_SMTP_ENABLED=false
# HYDRA_SMTP_HOST=smtp.example.com
# HYDRA_SMTP_PORT=587
# HYDRA_SMTP_USERNAME=
# HYDRA_SMTP_PASSWORD=
# HYDRA_SMTP_FROM_ADDRESS=noreply@hydra.local
# HYDRA_SMTP_FROM_NAME=Hydra

# Service Ports
HYDRA_API_PORT=8080
HYDRA_MCP_PORT=8081
HYDRA_WEB_PORT=3000

# CORS Origins (comma-separated, or * for all)
HYDRA_CORS_ORIGINS=*
EOF

    chmod 600 "$env_file"
    success "Environment file created: $env_file"
}

start_bundled_services() {
    info "Starting bundled data services..."

    cd "$PROJECT_DIR"

    # Start services
    docker compose --profile bundled up -d mongodb redis garage

    info "Waiting for services to be ready..."
    sleep 15

    # Check MongoDB
    if docker compose exec -T mongodb mongosh --eval "db.runCommand('ping')" &> /dev/null; then
        success "MongoDB is ready"
    else
        warn "MongoDB may still be initializing..."
    fi

    # Check Redis
    if docker compose exec -T redis redis-cli ping &> /dev/null; then
        success "Redis is ready"
    else
        warn "Redis may still be initializing..."
    fi

    # Initialize Garage bucket
    info "Initializing Garage storage..."

    # Wait a bit more for Garage
    sleep 5

    # Configure Garage layout (single-node setup)
    docker compose exec -T garage /garage layout assign -z dc1 -c 1G "$(docker compose exec -T garage /garage node id 2>/dev/null | cut -d'@' -f1)" 2>/dev/null || true
    docker compose exec -T garage /garage layout apply --version 1 2>/dev/null || true

    # Create bucket and key
    docker compose exec -T garage /garage bucket create hydra-bucket 2>/dev/null || info "Bucket may already exist"
    docker compose exec -T garage /garage key create hydra-key 2>/dev/null || info "Key may already exist"
    docker compose exec -T garage /garage bucket allow hydra-bucket --read --write --key hydra-key 2>/dev/null || true

    success "Bundled services started"
}

show_summary() {
    echo ""
    echo "=========================================="
    echo "       Hydra Data Layer Setup Complete"
    echo "=========================================="
    echo ""

    if [[ "$MODE" == "bundled" ]]; then
        info "Mode: Bundled (local Docker services)"
        echo ""
        info "Services:"
        echo "  - MongoDB:  mongodb://localhost:27017"
        echo "  - Redis:    redis://localhost:6379"
        echo "  - Garage:   http://localhost:3900 (S3 API)"
        echo ""
    else
        info "Mode: External"
        echo ""
        warn "Please update .env with your external service URLs"
        echo ""
    fi

    info "Configuration saved to: $PROJECT_DIR/.env"
    echo ""

    if [[ "$MODE" == "bundled" && "$GENERATE_ONLY" != "true" ]]; then
        info "To start Hydra API:"
        echo "  cd $PROJECT_DIR"
        echo "  docker compose up -d hydra-api"
        echo ""
        info "To view logs:"
        echo "  docker compose logs -f"
        echo ""
    fi

    warn "IMPORTANT: Keep your .env file secure - it contains secrets!"
    echo ""
}

main() {
    parse_args "$@"

    echo ""
    echo "=========================================="
    echo "     Hydra Data Layer Setup"
    echo "=========================================="
    echo ""

    check_dependencies
    generate_credentials
    write_env_file

    if [[ "$GENERATE_ONLY" == "true" ]]; then
        info "Generate-only mode: skipping service startup"
    elif [[ "$MODE" == "bundled" ]]; then
        start_bundled_services
    else
        info "External mode: configure your services in .env"
    fi

    show_summary
}

main "$@"
