"""Agent installation endpoints for curl-based deployments.

Supports multiple distribution methods:
- binary: Pre-compiled binaries from S3/Garage (default, fastest)
- obs: Bundled source from S3/Garage (Object Storage)
- local: Bundled source from local filesystem
"""

import re
from pathlib import Path
from typing import Literal

import structlog
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import Response, StreamingResponse

from hydra.api.v1 import __version__
from hydra.core.config import get_settings
from hydra.api.v1.core.deps import StorageServiceDep
from hydra.api.v1.services.storage import StorageSource

router = APIRouter(prefix="/agent", tags=["Agent Management"])
logger = structlog.get_logger(__name__)

# Version validation pattern (security: prevent path traversal)
VERSION_PATTERN = re.compile(r'^[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9]+)?$|^latest$')

# Supported targets for binary downloads
SUPPORTED_TARGETS = {
    "hydra-agent-linux-amd64": {"os": "linux", "arch": "amd64", "target": "linux-amd64"},
    "hydra-agent-linux-arm64": {"os": "linux", "arch": "arm64", "target": "linux-arm64"},
    "hydra-agent-linux-armv7": {"os": "linux", "arch": "armv7", "target": "linux-armv7"},
    "hydra-agent-darwin-amd64": {"os": "darwin", "arch": "amd64", "target": "darwin-amd64"},
    "hydra-agent-darwin-arm64": {"os": "darwin", "arch": "arm64", "target": "darwin-arm64"},
    "hydra-agent-freebsd-amd64": {"os": "freebsd", "arch": "amd64", "target": "freebsd-amd64"},
    "hydra-agent-windows-amd64": {"os": "windows", "arch": "amd64", "target": "windows-amd64"},
}


def validate_version(version: str) -> str:
    """Validate version parameter to prevent path traversal."""
    if not VERSION_PATTERN.match(version):
        raise HTTPException(
            status_code=400,
            detail={
                "error": {
                    "code": "INVALID_VERSION",
                    "message": f"Invalid version format: '{version}'",
                    "details": {"pattern": "X.Y.Z or X.Y.Z-suffix or latest"},
                }
            },
        )
    return version


def is_windows_user_agent(user_agent: str | None) -> bool:
    """Check if the user agent indicates a Windows client (PowerShell, etc.)."""
    if not user_agent:
        return False
    ua_lower = user_agent.lower()
    return any(marker in ua_lower for marker in [
        "powershell",
        "windowspowershell",
        "windows nt",
        "win64",
        "win32",
    ])


def get_powershell_installation_script(api_url: str, settings, source: StorageSource = StorageSource.BINARY, version: str = "latest") -> str:
    """Generate the PowerShell installation script for Windows.

    Args:
        api_url: Base API URL
        settings: Application settings
        source: Storage source (obs, local)
        version: Version to install
    """
    source_value = source.value
    return f'''#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Hydra Agent Installer for Windows (API wrapper)
    Generated by hydra-api v{__version__}

.DESCRIPTION
    Downloads and installs the Hydra Agent on Windows systems.

.PARAMETER Version
    Version to install (default: latest)

.PARAMETER InstallDir
    Installation directory (default: C:\\Program Files\\Hydra)

.PARAMETER RegisterToken
    Optional registration token for auto-registration

.PARAMETER CreateAlias
    Create 'hydra' alias for hydra-agent

.EXAMPLE
    iwr -useb {api_url}/agent/install | iex

.EXAMPLE
    iwr -useb "{api_url}/agent/install?version=0.3.1" | iex
#>

param(
    [string]$Version = "{version}",
    [string]$InstallDir = "$env:ProgramFiles\\Hydra",
    [string]$RegisterToken = "",
    [switch]$CreateAlias
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$ApiUrl = "{api_url}"
$Source = "{source_value}"

function Write-Info {{ param([string]$Message) Write-Host "[INFO] $Message" -ForegroundColor Blue }}
function Write-Success {{ param([string]$Message) Write-Host "[OK] $Message" -ForegroundColor Green }}
function Write-Warn {{ param([string]$Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }}
function Write-Err {{ param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }}

function Test-Administrator {{
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}}

if (-not (Test-Administrator)) {{
    Write-Err "This script requires Administrator privileges."
    Write-Err "Please run PowerShell as Administrator and try again."
    exit 1
}}

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "   Hydra Agent Installer (Windows)"
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Create directories
Write-Info "Creating directories..."
$ConfigDir = "C:\\ProgramData\\Hydra"
$VaultDir = "C:\\ProgramData\\Hydra\\vault"
$LogDir = "C:\\ProgramData\\Hydra\\logs"

foreach ($dir in @($InstallDir, $ConfigDir, $VaultDir, $LogDir)) {{
    if (-not (Test-Path $dir)) {{
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }}
}}

# Set secure permissions on vault directory
Write-Info "Setting secure permissions on vault..."
$acl = Get-Acl $VaultDir
$acl.SetAccessRuleProtection($true, $false)
$adminRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
)
$systemRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow"
)
$acl.AddAccessRule($adminRule)
$acl.AddAccessRule($systemRule)
Set-Acl -Path $VaultDir -AclObject $acl

# Download binary
$DownloadUrl = "$ApiUrl/agent/download?source=binary&target=windows-amd64&version=$Version"
$BinaryPath = "$InstallDir\\hydra-agent.exe"

Write-Info "Downloading hydra-agent (version: $Version)..."
try {{
    Invoke-WebRequest -Uri $DownloadUrl -OutFile $BinaryPath -UseBasicParsing
    Write-Success "Downloaded hydra-agent.exe"
}} catch {{
    Write-Err "Failed to download binary: $_"
    exit 1
}}

# Create alias if requested
if ($CreateAlias) {{
    $AliasPath = "$InstallDir\\hydra.exe"
    if (Test-Path $AliasPath) {{ Remove-Item $AliasPath -Force }}
    Copy-Item $BinaryPath $AliasPath
    Write-Info "Created alias: hydra.exe"
}}

# Add to PATH if not already present
$EnvPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
if ($EnvPath -notlike "*$InstallDir*") {{
    Write-Info "Adding to system PATH..."
    [Environment]::SetEnvironmentVariable("Path", "$EnvPath;$InstallDir", "Machine")
    $env:Path = "$env:Path;$InstallDir"
    Write-Success "Added to PATH"
}}

# Create default config if not exists
$ConfigFile = "$ConfigDir\\agent.toml"
if (-not (Test-Path $ConfigFile)) {{
    Write-Info "Creating default configuration..."
    @"
# Hydra Agent Configuration
# Edit this file to configure the agent

[node]
node_id = "CHANGE_ME"
class = "compute"
node_type = "physical"

[api]
url = "$ApiUrl"
timeout_seconds = 30
retries = 3

[collection]
level = "neutral"
include_packages = true
include_users = true

[schedule]
enabled = true
interval_seconds = 21600
on_startup = true
"@ | Set-Content -Path $ConfigFile -Encoding UTF8
    Write-Success "Created config at $ConfigFile"
}}

# Register with token if provided
if ($RegisterToken) {{
    Write-Info "Registering with provided token..."
    & "$BinaryPath" register --token $RegisterToken
}}

Write-Host ""
Write-Success "Installation complete!"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Edit config: $ConfigFile"
Write-Host "  2. Login: hydra-agent login -u <username>"
Write-Host "  3. Register: hydra-agent register"
Write-Host "  4. Register node: hydra-agent node register"
Write-Host "  5. Install service: hydra-agent service install"
Write-Host ""
'''


def get_installation_script(api_url: str, settings, source: StorageSource = StorageSource.BINARY, version: str = "latest") -> str:
    """Generate the bash installation script with embedded API URL.

    Args:
        api_url: Base API URL
        settings: Application settings
        source: Storage source (obs, local)
        version: Version to install
    """
    source_value = source.value
    return fr'''#!/bin/bash
#
# Hydra Agent Installer (API wrapper)
# Generated by hydra-api v{__version__}
#
# Usage:
#   curl -sSL {api_url}/agent/install?source=local|obs | bash -s -- [OPTIONS]
#
# Options (forwarded to hydra-agent/scripts/install.sh):
#   -v, --version <VER>     Version number for binary manifest (required)
#   -h, --help              Show help
#   -a, --aliased           Create 'hydra' alias
#   -g, --global            Add to PATH globally
#   -d, --install-dir <DIR> Installation directory [default: /usr/local/bin]
#   -c, --config <PATH>     Config file path [default: /etc/hydra/agent.toml]
#   -r, --register <TOKEN>  Auto-register with token after install
#
set -euo pipefail

API_URL="{api_url}"
SOURCE="{source_value}"
DEFAULT_VERSION="{version}"

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

info()    {{ echo -e "${{BLUE}}[INFO]${{NC}} $*"; }}
warn()    {{ echo -e "${{YELLOW}}[WARN]${{NC}} $*"; }}
error()   {{ echo -e "${{RED}}[ERROR]${{NC}} $*" >&2; }}
success() {{ echo -e "${{GREEN}}[OK]${{NC}} $*"; }}

TMP_DIR=""
AGENT_ROOT=""
INSTALL_SCRIPT=""
USER_ARGS=()
REQUESTED_VERSION=""
HAS_VERSION="false"

parse_args() {{
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -v|--version)
                if [[ -z "${{2:-}}" ]]; then
                    error "Missing value for $1"
                    exit 1
                fi
                REQUESTED_VERSION="$2"
                HAS_VERSION="true"
                USER_ARGS+=("$1" "$2")
                shift 2
                ;;
            *)
                USER_ARGS+=("$1")
                shift
                ;;
        esac
    done
}}

check_prereqs() {{
    if ! command -v curl >/dev/null 2>&1; then
        error "curl is required but not installed"
        exit 1
    fi
    if ! command -v unzip >/dev/null 2>&1; then
        error "unzip is required but not installed"
        exit 1
    fi
}}

download_bundle() {{
    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT

    local download_url="$API_URL/agent/download?source=$SOURCE&version=$REQUESTED_VERSION"
    info "Downloading agent bundle (source=$SOURCE, version=$REQUESTED_VERSION)..."

    curl -sSL -f -o "$TMP_DIR/hydra-agent.zip" "$download_url" || {{
        error "Failed to download agent bundle"
        exit 1
    }}

    info "Extracting bundle..."
    mkdir -p "$TMP_DIR/bundle"
    unzip -q "$TMP_DIR/hydra-agent.zip" -d "$TMP_DIR/bundle" || {{
        error "Failed to extract bundle"
        exit 1
    }}
}}

find_installer() {{
    local install_script
    install_script=$(find "$TMP_DIR/bundle" -path "*/scripts/install.sh" -type f | head -1)
    if [[ -z "$install_script" ]]; then
        error "install.sh not found in bundle"
        exit 1
    fi

    AGENT_ROOT=$(cd "$(dirname "$install_script")/.." && pwd)
    INSTALL_SCRIPT="$install_script"
}}

run_installer() {{
    info "Running hydra-agent installer..."
    (cd "$AGENT_ROOT" && HYDRA_API_URL="$API_URL" bash "$INSTALL_SCRIPT" "${{USER_ARGS[@]}}")
}}

main() {{
    if [[ "$SOURCE" != "obs" && "$SOURCE" != "local" ]]; then
        error "Unsupported source for /agent/install: $SOURCE"
        error "Use ?source=local or ?source=obs"
        exit 1
    fi

    parse_args "$@"

    if [[ "$HAS_VERSION" != "true" ]]; then
        REQUESTED_VERSION="$DEFAULT_VERSION"
        USER_ARGS+=("-v" "$REQUESTED_VERSION")
    fi

    check_prereqs
    download_bundle
    find_installer
    run_installer
}}

main "$@"
'''


@router.get(
    "/install",
    summary="Installation Script",
    description="Returns an installation script for agent deployment. Auto-detects Windows clients via User-Agent and returns PowerShell script.",
    response_class=Response,
    responses={
        200: {
            "description": "Installation script (bash for Unix, PowerShell for Windows)",
            "content": {
                "text/x-shellscript": {},
                "text/plain": {},
            },
        }
    },
)
async def get_install_script(
    request: Request,
    arch: Literal["amd64", "arm64", "armv7"] | None = Query(
        default=None, description="Target architecture (auto-detect if not specified)"
    ),
    os: Literal["linux", "darwin", "freebsd", "windows"] | None = Query(
        default=None, description="Target OS (auto-detect from User-Agent if not specified)"
    ),
    source: StorageSource = Query(
        default=StorageSource.BINARY,
        description="Storage source: binary (pre-compiled), obs (S3 bundles), local (local bundles)",
    ),
    version: str = Query(default="latest", description="Agent version to install"),
) -> Response:
    """
    Generate and return the installation script.

    The API URL in the generated script is derived from the request URL. Use HTTP for
    local development/testing and HTTPS for production.

    For Unix systems (curl):
    ```bash
    # Local development (HTTP)
    curl -sSL http://localhost:8080/api/v1/agent/install?source=local | bash -s -- -v 0.3.1

    # Production (HTTPS)
    curl -sSL https://hydra.local/api/v1/agent/install?source=local | bash -s -- -v 0.3.1
    ```

    For Windows (PowerShell):
    ```powershell
    # Local development
    iwr -useb http://localhost:8080/api/v1/agent/install | iex

    # Production
    iwr -useb https://hydra.local/api/v1/agent/install | iex
    ```

    The endpoint auto-detects Windows clients via User-Agent and returns a PowerShell script.
    Use ?os=windows to force PowerShell output, or ?os=linux to force bash output.
    """
    # Determine API URL from request
    api_url = str(request.base_url).rstrip("/")
    if request.url.path.startswith("/api/v1"):
        api_url = f"{api_url.rsplit('/api/v1', 1)[0]}/api/v1"
    else:
        api_url = f"{api_url}/api/v1"

    version = validate_version(version)

    # Detect if this is a Windows client
    user_agent = request.headers.get("user-agent")
    is_windows = os == "windows" or (os is None and is_windows_user_agent(user_agent))

    settings = get_settings()

    if is_windows:
        # Windows clients get PowerShell script with binary source
        script = get_powershell_installation_script(api_url, settings, source=StorageSource.BINARY, version=version)

        logger.info(
            "install_script_generated",
            api_url=api_url,
            requested_arch=arch,
            requested_os=os or "windows (auto-detected)",
            source="binary",
            version=version,
            script_type="powershell",
            user_agent=user_agent,
        )

        return Response(
            content=script,
            media_type="text/plain",
            headers={
                "Content-Disposition": 'attachment; filename="hydra-install.ps1"',
                "X-Hydra-Version": __version__,
                "X-Script-Type": "powershell",
            },
        )

    # Unix clients (bash script)
    if source == StorageSource.BINARY:
        raise HTTPException(
            status_code=400,
            detail={
                "error": {
                    "code": "UNSUPPORTED_SOURCE",
                    "message": "Binary source is not supported for Unix /agent/install. Use ?source=local or ?source=obs for source bundle installation, or download binary directly via /agent/download.",
                    "details": {"allowed_sources": ["local", "obs"]},
                }
            },
        )

    script = get_installation_script(api_url, settings, source=source, version=version)

    logger.info(
        "install_script_generated",
        api_url=api_url,
        requested_arch=arch,
        requested_os=os,
        source=source.value,
        version=version,
        script_type="bash",
    )

    return Response(
        content=script,
        media_type="text/x-shellscript",
        headers={
            "Content-Disposition": 'attachment; filename="hydra-install.sh"',
            "X-Hydra-Version": __version__,
            "X-Script-Type": "bash",
        },
    )


@router.get(
    "/download",
    summary="Download Agent Bundle or Binary",
    description="Download agent bundle (source) or binary based on storage source.",
    response_class=Response,
    response_model=None,
    responses={
        200: {
            "description": "Agent bundle or binary file",
            "content": {
                "application/octet-stream": {},
                "application/zip": {},
            },
        },
        404: {"description": "Version not found"},
        503: {"description": "Storage not configured"},
    },
)
async def download_agent(
    storage: StorageServiceDep,
    source: StorageSource = Query(
        default=StorageSource.BINARY,
        description="Storage source: binary (pre-compiled), obs (S3 bundles), local (local bundles)",
    ),
    version: str = Query(default="latest", description="Agent version"),
    target: str | None = Query(
        default=None,
        description="Target architecture (required for source=binary, e.g., linux-amd64)",
    ),
) -> Response:
    """
    Download agent based on storage source.

    For source=binary:
    - Downloads pre-compiled binary for specified target
    - Requires 'target' parameter (e.g., linux-amd64, darwin-arm64)

    For source=obs or source=local:
    - Downloads bundled source code (zip)
    - Architecture-independent, built locally during installation
    """
    from hydra.api.v1.services.storage import (
        ObjectNotFoundError,
        StorageUnavailableError,
        StorageNotConfiguredError,
        S3BundleStorageService,
        LocalBundleStorageService,
    )

    # Validate version (security: prevent path traversal)
    version = validate_version(version)

    # Check if storage is configured
    if storage is None:
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "STORAGE_NOT_CONFIGURED",
                    "message": "No storage backend is configured.",
                }
            },
        )

    # Check if requested source is available
    if not storage.is_source_available(source):
        available = [s.value for s in storage.get_available_sources()]
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "SOURCE_NOT_CONFIGURED",
                    "message": f"Storage source '{source.value}' is not configured.",
                    "details": {"available_sources": available},
                }
            },
        )

    try:
        backend = storage.get_backend(source)

        if source == StorageSource.BINARY:
            # Binary download requires target
            if not target:
                raise HTTPException(
                    status_code=400,
                    detail={
                        "error": {
                            "code": "TARGET_REQUIRED",
                            "message": "Target architecture is required for binary downloads",
                            "details": {
                                "available_targets": [
                                    t["target"] for t in SUPPORTED_TARGETS.values()
                                ]
                            },
                        }
                    },
                )

            # Validate target
            valid_targets = {t["target"] for t in SUPPORTED_TARGETS.values()}
            if target not in valid_targets:
                raise HTTPException(
                    status_code=400,
                    detail={
                        "error": {
                            "code": "INVALID_TARGET",
                            "message": f"Invalid target: {target}",
                            "details": {"available_targets": list(valid_targets)},
                        }
                    },
                )

            # Resolve 'latest' to actual version
            resolved_version = version
            if version == "latest":
                resolved_version = await backend.get_latest_version(target)
                if not resolved_version:
                    raise HTTPException(
                        status_code=404,
                        detail={
                            "error": {
                                "code": "NO_VERSIONS_AVAILABLE",
                                "message": f"No versions available for target {target}",
                            }
                        },
                    )

            # Build the storage key (Windows binaries have .exe extension)
            binary_name = "hydra-agent.exe" if target.startswith("windows") else "hydra-agent"
            object_key = f"agents/{target}/{resolved_version}/{binary_name}"
            filename = f"hydra-agent-{target}" + (".exe" if target.startswith("windows") else "")
            media_type = "application/octet-stream"

        else:
            # Bundle download (obs or local)
            resolved_version = version
            if version == "latest":
                resolved_version = await backend.get_latest_version()
                if not resolved_version:
                    raise HTTPException(
                        status_code=404,
                        detail={
                            "error": {
                                "code": "NO_VERSIONS_AVAILABLE",
                                "message": "No bundle versions available",
                            }
                        },
                    )

            # Get bundle key from backend
            object_key = backend.get_bundle_key(resolved_version)
            filename = f"hydra-agent-{resolved_version}.zip"
            media_type = "application/zip"

        # Get metadata for response headers
        metadata = await backend.get_object_metadata(object_key)

        logger.info(
            "agent_download",
            source=source.value,
            version=resolved_version,
            target=target,
            key=object_key,
            size=metadata.get("size"),
        )

        # Stream the file
        async def stream_file():
            async for chunk in backend.get_object_stream(object_key):
                yield chunk

        headers = {
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-Hydra-Version": resolved_version,
            "X-Storage-Source": source.value,
        }
        if metadata.get("size"):
            headers["Content-Length"] = str(metadata["size"])
        if metadata.get("sha256"):
            headers["X-Checksum-SHA256"] = metadata["sha256"]

        return StreamingResponse(
            stream_file(),
            media_type=media_type,
            headers=headers,
        )

    except StorageNotConfiguredError as e:
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "SOURCE_NOT_CONFIGURED",
                    "message": str(e),
                }
            },
        )
    except ObjectNotFoundError as e:
        raise HTTPException(
            status_code=404,
            detail={
                "error": {
                    "code": "NOT_FOUND",
                    "message": f"Version {version} not found",
                    "details": {
                        "source": source.value,
                        "version": version,
                        "target": target,
                    },
                }
            },
        )
    except StorageUnavailableError as e:
        logger.error(
            "storage_unavailable",
            source=source.value,
            version=version,
            error=str(e),
        )
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "STORAGE_UNAVAILABLE",
                    "message": "Storage is temporarily unavailable",
                }
            },
        )


@router.get(
    "/versions",
    summary="List Agent Versions",
    description="List available agent versions for all supported targets or bundles.",
    responses={
        200: {
            "description": "Version manifest",
            "content": {"application/json": {}},
        },
        503: {
            "description": "Storage not configured",
        },
    },
)
async def list_versions(
    storage: StorageServiceDep,
    source: StorageSource = Query(
        default=StorageSource.BINARY,
        description="Storage source: binary (pre-compiled), obs (S3 bundles), local (local bundles)",
    ),
) -> dict:
    """
    List available agent versions.

    For source=binary:
    - Returns versions per target architecture
    - Requires S3-compatible object storage

    For source=obs or source=local:
    - Returns bundled source versions
    - Architecture-independent (built locally)
    """
    from hydra.api.v1.services.storage import StorageUnavailableError, StorageNotConfiguredError

    # Check if storage is configured
    if storage is None:
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "STORAGE_NOT_CONFIGURED",
                    "message": "No storage backend is configured.",
                    "details": {"requested_source": source.value},
                }
            },
        )

    # Check if requested source is available
    if not storage.is_source_available(source):
        available = [s.value for s in storage.get_available_sources()]
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "SOURCE_NOT_CONFIGURED",
                    "message": f"Storage source '{source.value}' is not configured.",
                    "details": {"available_sources": available},
                }
            },
        )

    manifest = {
        "schemaVersion": 1,
        "latestVersion": __version__,
        "source": source.value,
        "availableSources": [s.value for s in storage.get_available_sources()],
    }

    try:
        backend = storage.get_backend(source)

        if source == StorageSource.BINARY:
            # Binary mode: list per-target versions
            manifest["targets"] = {}

            for target_name, target_info in SUPPORTED_TARGETS.items():
                target = target_info["target"]

                try:
                    logger.debug("listing_versions_for_target", target=target, source=source.value)
                    versions = await backend.list_versions(target)
                    latest = await backend.get_latest_version(target)

                    logger.debug(
                        "versions_found",
                        target=target,
                        version_count=len(versions),
                        latest=latest,
                    )

                    if versions:
                        manifest["targets"][target] = {
                            "latest": latest or (versions[0]["version"] if versions else None),
                            "versions": versions,
                        }
                    else:
                        manifest["targets"][target] = {
                            "latest": None,
                            "versions": [],
                            "status": "no_binaries_available",
                        }
                except StorageUnavailableError as e:
                    logger.warning("storage_unavailable_for_target", target=target, error=str(e))
                    manifest["targets"][target] = {
                        "latest": None,
                        "versions": [],
                        "status": "storage_unavailable",
                    }
                except Exception as e:
                    logger.warning(
                        "list_versions_error",
                        target=target,
                        error=str(e),
                        error_type=type(e).__name__,
                    )
                    manifest["targets"][target] = {
                        "latest": None,
                        "versions": [],
                        "status": "error",
                        "error": str(e),
                    }
        else:
            # Bundle mode (obs or local): architecture-independent
            versions = await backend.list_versions()
            latest = await backend.get_latest_version()

            manifest["bundles"] = {
                "latest": latest,
                "versions": versions,
            }

    except StorageNotConfiguredError as e:
        raise HTTPException(
            status_code=503,
            detail={
                "error": {
                    "code": "SOURCE_NOT_CONFIGURED",
                    "message": str(e),
                }
            },
        )

    logger.info("versions_listed", source=source.value)

    return manifest
